### ISSUE TITLE
Support for LTSB 1607

### ISSUE THREAD

**Issue by Qiangong2** [microsoft/winget-cli#1008]
# Description of the new feature/enhancement

Currently in our production environment we use choco to manage an internal repository of applications. However, now that winget has reached v1.0, we would like to use it instead. Unfortunately, winget does not support 1607 at the moment.

# Proposed technical implementation details (optional)

Support to run winget on LTSB 1607

**Comment by nonbob** [comment]
I work at a place the does corporate (not personal) financial software.  Foot-dragging is the rule.  I know of no servers running 2019 (other than a couple of small experimental VMs that I installed myself).  2016 is what the "new" (recently built) servers run. 2012R2 is the rule (and there is scattered older stuff on VMs that support legacy software), because OS end-of-life announcements are what drives upgrades (really).  And I know our shop is note alone in this regard.  Chocolatey is happy with all of these.  And I **really** appreciate that WMF 5.1 was back-ported.

Windows (telemetry) phones home all the time - somebody at Microsoft must have some stats on this kind of thing.

I appreciate the direction that Microsoft has taken over the last few years.  I just don't get to participate all the time.:-(  Luckily, because Windows 7 is dead and nobody wants (or wants to support) 8 and 8.1 on the desktop, we at least get to run Windows 10 on our personal dev machines.

**Comment by denelon** [comment]
Unfortunately, this version of Windows is well outside of our support boundaries. WinGet still works down to Windows 10 RS5, and we don't plan on introducing any breaking changes.

I'm going to close this issue as not planned.
