### ISSUE TITLE
Make "Update" an alias for "Upgrade"

### ISSUE THREAD

**Issue by BruceHarrison** [microsoft/winget-cli#1026]
Greetings,

Is it possible to make "update" an alias for the "upgrade" command? 

I keep thinking that the command is: WinGet update SomeApp

I doubt I am the only one making this mistake.

Appreciatively,
-Bruce

**Comment by pjaj** [comment]
I was thinking of suggesting the same.

**Comment by cokedupking** [comment]
Usually "update" means "look at the repo servers to see what upgrades are available" and "upgrade" means "install the latest version of the software that your computer knows about". So usually you would update and then upgrade to install the newest version, or upgrade to install a specific version. For some weird reason, Microsoft decided to make "upgrade" do both and not allow an "update" option, which means you'll always need internet and are forced to install the newest available version (which should be fine for 97% of people, but those 3% are really left out)

**Comment by denelon** [comment]
We had quite the discussion around "upgrade" vs. "update". The "update" verb was used for refreshing the PreIndexed package cache with pointers to manifests. It's used by "search" to see which packages are available. The overwhelming majority preferred "upgrade". We are likely to address this topic again as we work towards implementing native PowerShell support.

**Comment by denelon** [comment]
The behavior for "upgrade" was modified since we didn't have support for "pin" to lock a version of a package and prevent it from being upgraded. If you `winget upgrade` you will see a list of packages that may be upgraded. You may use the `--version` argument to specify the version you want to upgrade to. You can `winget show <package> --versions` to see the list of versions available from a source.

**Comment by pjaj** [comment]
I think the problem here is the difference between the developers who use very specific interpretations  of the words and the end user who does not. There are many programs that offer to "update" themselves when a new version is available or at least have a "check for updates" option.  There are other utilities that are designed to "update" programs and drivers etc. I've never seen one of them offer to "upgrade" or with "upgrade" in their name.
Even MS's own site only talks about "update" not "upgrade" for most things.
Are you developing a utility that satisfies the aesthetics of the developers or one that does not confuse the end users?
It sure as heck confused me as, after 60 years of using computers, I automatically typed -update the first time I tried it.

**Comment by iDolmatov** [comment]
Met with a similar problem of understanding. The program used both words for different tasks. In the Russian version, one word is used. The differences are only in its form.
![image](https://user-images.githubusercontent.com/19782385/120371231-f3bb9180-c32e-11eb-80a3-9a5be911f504.png)
![image](https://user-images.githubusercontent.com/19782385/120371272-fd44f980-c32e-11eb-8599-c5f753fd116d.png)

There is also a difference in Linux.
https://help.ubuntu.com/community/AptGet/Howto
See "Maintenance commands".
It is logical to do the same in order to update the database without searching. For example, for the list and show commands.

**Comment by Trenly** [comment]
If anyone has any strong opinions on aliases, i.e, if any others should be added, please post a comment on the linked PR
