### ISSUE TITLE
List installed Apps

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#119]
As a user I want to be able to see what winget has installed on my machine and if an update is available so I don't have to manually do updates for each program.

**Experimental Feature**
`winget list` - displays installed packages (includes programs in Add/Remove Programs).
`winget list -?` - displays help for the list command.
`winget list <package>` - displays installed packages filtered by `<package>`.

Note: upgrade depends on list also being enabled.

winget features - displays all experimental features and their status
winget settings - launches settings.json to configure settings like experimental features

Edited: experimental status

**Comment by jantari** [comment]
I will once again suggest `apt` syntax:

```powershell
winget list # lists apps installed by winget
winget list --upgradable # lists only installed apps with available updates
```

**Comment by KevinLaMS** [comment]
I have an early draft started of the spec.
#397

**Comment by mhm13dev** [comment]
When this feature is coming out? Any date?

**Comment by denelon** [comment]
@mhm13dev we do not have a date identified, but it is targeted for v0.3.x. For reference, the v0.2.x is targeted as support for installing store apps. That work is in progress, so this will be coming soon. Any dates on milestones are just used to help with sorting and do not reflect an actual target release date.

**Comment by WSLUser** [comment]
> Does anyone have a use case that requires explicitly tracking everything installed by winget?

Chocolately can do this. More than that, knowing which software was installed if a bunch of things were installed with winget and even more importantly, knowing which ones need an update is helpful. I do think there should be a separate flag for checking if a winget package is update-able. Also this helps if you need to migrate to a new machine/VM/cloud instance so you don't forget what to install. Ideally we could take the output and put in a text file. A followup could be using that text file on the new machine to grab the packages.

**Comment by denelon** [comment]
@mhm13dev this feature is in the current version in an experimental mode.

**Comment by brwilkinson** [comment]
when I test out the experimental feature, I am not sure on the expectations . . so I have some q's.

When I run the following:

```powershell
winget list | sls -Pattern powershell
```
![image](https://user-images.githubusercontent.com/3605266/99572685-e25df980-2989-11eb-87e5-b9569fabda6e.png)

I only see the MSStore version that is installed [7.2.1.0], not the other non store version e.g. [7.1.0]

However I do actually have the other version installed..

![image](https://user-images.githubusercontent.com/3605266/99572883-2e10a300-298a-11eb-9dd5-ea73a250a77b.png)

Am I missing something or is this because it's still experimental ? OR is the expectation that only the MSStore apps will be upgradable ?

**Comment by JohnMcPMS** [comment]
@brwilkinson , the work to also list the entries that you would expect from Add/Remove Programs is coming soon (in master, but we are flighting it internally still).  It is definitely our goal to have everything that you can install through winget also show up in list and be able to upgrade and uninstall.

**Comment by brwilkinson** [comment]
Thanks @JohnMcPMS 

I wasn't sure, since I half expected Winget to keep track of what it installed and be able to list them out or upgrade them.

**Comment by JohnMcPMS** [comment]
@brwilkinson , that too is coming soon.

**Comment by github-account1111** [comment]
> 
> 
> Do you care about differentiating packages installed by winget vs packages installed outside of it? I don't see the value in treating them differently. I could potentially see value in this for upgrade, but it would make more sense to provide a way to pin a package to a specific version, preventing it from being upgraded. This could apply to any package.
> 
> Does anyone have a use case that requires explicitly tracking everything installed by winget?

Yes that's like.. essential. If something breaks I know where to look. Also to see how "fully" I've transitioned to winget.

**Comment by superusercode** [comment]
A minor issue with the current implementation of `winget list` is that it does not show manually hidden apps from the program install list. Programs are hidden officially using via the registry by installers and sysadmins, but they can also be hidden manually by the user using [Hide from Uninstall List](https://www.sordum.org/11081/hide-from-uninstall-list-v1-0/) and similar programs.

i.e. 
![image](https://user-images.githubusercontent.com/60588434/117094622-42770b00-ad32-11eb-9dc0-e43113db1a57.png)


Ideally programs should be visible regardless of status (shown/hidden), or at the very least visible when combined with a flag (winget list -hidden) or winget is run as an admin.

**Comment by ecovio1** [comment]
@denelon ⬆⬆..  a `-hidden `flag will be nice from a `running as admin shell.`

this is mostly done _per app basis_  via 
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall
or 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

under a program folder , 
creating a new dword value , where  Value Name is  SystemComponent and Value Data is  1. 
or  manually renaming the program's DisplayName key to anything else random.

or   hiding the whole "Programs and Features page" completely _per user basis_ 
from GPolicy>User Configuration > Administrative Templates > Control Panel > Programs.

**Comment by denelon** [comment]
@ecovio1 I'll take a look at the idea of -hidden as an argument for list.

**Comment by naikrovek** [comment]
So this is maybe not the proper forum for me to ask this, but since it's related to installation and uninstallation, I'll mention it.

Do things installed with WinGet need to be "installed" at all?  I have become a true fan of .zip distribution of software, whenever it's possible to do that.  Download a .zip, extract that to a folder, run the .exe within, which is not an installer, but the application itself.  I'm free to move that folder around at will, and nothing breaks.  I don't understand why software needs to be "installed" at all, anymore.  It is arbitrary, adds all kinds of complexity, and provides no solid benefits over "a folder with an application in it" that I can see.  I'll admit that I don't know what info this installation system does actually make available.

There can still be a central list of software that you have, where you can go to remove something if you like, but you could also just delete the folder with the application and it would be removed from the central list.

I know that installers aren't going anywhere, and a new software installation and maintenance system is being developed here; does it HAVE to continue to do things the same way?  This is, potentially, an opportunity to do things a new way.  There's nothing that could be improved or simplified?

**Comment by binarylandscapes** [comment]
> So this is maybe not the proper forum for me to ask this, but since it's related to installation and uninstallation, I'll mention it.
> 
> Do things installed with WinGet need to be "installed" at all? I have become a true fan of .zip distribution of software, whenever it's possible to do that. Download a .zip, extract that to a folder, run the .exe within, which is not an installer, but the application itself. I'm free to move that folder around at will, and nothing breaks. I don't understand why software needs to be "installed" at all, anymore. It is arbitrary, adds all kinds of complexity, and provides no solid benefits over "a folder with an application in it" that I can see. I'll admit that I don't know what info this installation system does actually make available.
> 
> There can still be a central list of software that you have, where you can go to remove something if you like, but you could also just delete the folder with the application and it would be removed from the central list.
> 
> I know that installers aren't going anywhere, and a new software installation and maintenance system is being developed here; does it HAVE to continue to do things the same way? This is, potentially, an opportunity to do things a new way. There's nothing that could be improved or simplified?

1. You are misunderstanding the goal of winget, its not a new software and installation maintenance system. It is giving windows the same/similar system linux/unix systems use. Not trying to reinvent the wheel here.
2. Yes, while it's great everything you seem to use is a portable app and can be self-contained and moved at will, most applications do not and this software maintenance is for system administrator to better maintain their responsible system and maintain good configuration management. IMO portable applications have their place but not in an enterprise or CM-driven environment.
3. It sounds like you would never even need to use Winget for your purposes. Powershell or Shell scripts to unzip/replace and sha  & compare a directory sounds like what you need for your environment, which can be done and maintained on your own. I assume you want no security of being able to remove or install apps since it all zip files/folder and can be changed/added/deleted at will. Unless what you are really trying to suggest is that all app developers for all operating systems change to a zip deployment model only. If that is the case, then this isn't the proper forum to change that mentality and I for one dont agree with that mentality for security, CM, and a host of reasons but good luck to you in that endeavor.

**Comment by naikrovek** [comment]
winget is used to install and remove software from Windows, right?  

and winget authors are free to choose what installation and uninstallation method is employed for that purpose, right?

and in 1000 years, software installation will not be the same as it is today, I think that's a fair assumption to make.

so at some point within 1000 years, a new software installation and uninstallation system will be developed.  at least one.  probably hundreds, but let's not try to predict that.

at whatever point a new installation system is created, i hope the author of that system really tries to understand what is actually happening when software is installed:  files are placed on a filesystem, and a record of their addition is made.

there is no reason that this cannot happen with winget and packages distributed as .zip files.

that is what I am trying to say.

you don't have to be so dismissive, by the way.

**Comment by Fooughhy** [comment]
> So this is maybe not the proper forum for me to ask this, but since it's related to installation and uninstallation, I'll mention it.
> 
> Do things installed with WinGet need to be "installed" at all? I have become a true fan of .zip distribution of software, whenever it's possible to do that. Download a .zip, extract that to a folder, run the .exe within, which is not an installer, but the application itself. I'm free to move that folder around at will, and nothing breaks. I don't understand why software needs to be "installed" at all, anymore. It is arbitrary, adds all kinds of complexity, and provides no solid benefits over "a folder with an application in it" that I can see. I'll admit that I don't know what info this installation system does actually make available.
> 
> There can still be a central list of software that you have, where you can go to remove something if you like, but you could also just delete the folder with the application and it would be removed from the central list.
> 
> I know that installers aren't going anywhere, and a new software installation and maintenance system is being developed here; does it HAVE to continue to do things the same way? This is, potentially, an opportunity to do things a new way. There's nothing that could be improved or simplified?

Hope you have checked out [Scoop](https://github.com/lukesampson/scoop).

**Comment by denelon** [comment]
@naikrovek Windows can be a complex ecosystem to maintain. We are looking at adding support for .zip #140 and portable/standalone (loose) .exe #182 packages in the Windows Package Manager. It's likely we will include registering the package via Add / Remove Programs to support upgrade and uninstall scenarios. Unfortunately, that also likely means we become dependent on the location the files are initially placed. If a user moves them after the fact, we would essentially loose track of them.

**Comment by naikrovek** [comment]
OneDrive knows when I move files vs deleting them from one location and then putting new files in a new location.  Surely these wonderful Turing-complete computers that we have can solve issues like this.

**Comment by superusercode** [comment]
@denelon should I make a separate issue for listing hidden apps?

**Comment by denelon** [comment]
@superusercode, yes please. Sorry I missed this one. I recently scrubbed all of the features for other scope, and sadly I missed this.

**Comment by superusercode** [comment]
> @superusercode, yes please. Sorry I missed this one. I recently scrubbed all of the features for other scope, and sadly I missed this.

now listed at #977

**Comment by CumpsD** [comment]
What happened to `--upgradable`?

> I will once again suggest `apt` syntax:
> 
> ```powershell
> winget list # lists apps installed by winget
> winget list --upgradable # lists only installed apps with available updates
> ```

**Comment by hubertsvk** [comment]
hello,
I would like to show list of all installed software from specific source
` winget list --source winget`
and I get list of software that is installed from all source why?
![image](https://user-images.githubusercontent.com/38318597/152742996-78fda941-182f-4370-927a-a4839a785e7f.png)

**Comment by denelon** [comment]
@hubertsvk take a look at #1155

**Comment by Cyberavater** [comment]
How do I list packages by install date? [descending or(/and) ascending ].

**Comment by denelon** [comment]
I added "sort" to:
* https://github.com/microsoft/winget-cli/issues/1155
