### ISSUE TITLE
Pls, add Microsoft products 

### ISSUE THREAD

**Issue by SlimRG** [microsoft/winget-cli#1233]
Hi!
I start use your app (winget)
It's very usefull for me, but there only a few official Microsoft Apps.
I can't install 365 office (but can do it through official site), can't install Skype (UWP version), can't install updates for Windows 10, can't install Teams (known bug), can't install windows modules (like .NET Framework 4.5 or DirectX) and can't install many other things by Microsoft that I can download for free* from official site.
* When I say "free" - I mean I can download app download app for free (inside app can be licensing page, in office, for example)
So, today I see lot's of usefull and useless apps in apps list, but I don't see products from Microsoft.
In my opinion, if Microsoft made app manager, so it should use it. Or this manager isn't a part of ecosystem Microsoft?! If it is not a part, so for what you have made it?
Thanks!
P.S. Sorry for my English, I'm from Russia

**Comment by denelon** [comment]
@SlimRG we're working with several other internal teams here at Microsoft to expand the catalog. Many of them have already started automating the process to publish their packages (Windows Terminal, PowerShell, PowerToys, Visual Studio Code, etc.).

I believe you can `winget install microsoft.office` to get Microsoft 365 Apps for enterprise. Many of the >NET Frameworks are available. Try `winget search .net` to see which ones are already in the community repository.

We do want all software to be available for users. The community has also been adding many of the packages currently supported by the Windows Package Manager. Several of them aren't fully supported yet due to installer limitations, or limitations in the Windows Package Manager itself. We're working on it.

**Comment by SlimRG** [comment]
Thank you very much!
I don't know that ofiice is here: winget install microsoft.office
I'm sorry - you are the best

**Comment by denelon** [comment]
No worries, and your English is likely to be infinitely better than my Russian 😊
