### ISSUE TITLE
Add support for Batchfile parsing

### ISSUE THREAD

**Issue by DeveloperWOW64** [microsoft/winget-cli#1332]
# Description of the new feature/enhancement

I am trying to create an installer for my latest project, [Desktop Management](https://github.com/deskmgr/)
And I have coded it in [Batchfile](https://github.com/deskmgr/app/tree/main/.winget/). However, Winget cannot parse Batchfile. I know I can easily just use A bat2exe converter, which in my case, I will use, but I thought it would be a good idea if in the future Winget could understand a .bat file as an installler.

**Comment by sredna** [comment]
I suppose what you are asking is not for WinGet to add a batchfile parser but rather the ability to specify batch as a installer type and have WinGet invoke `cmd.exe /c installer.bat`.

**Comment by DeveloperWOW64** [comment]
yes

**Comment by ItzLevvie** [comment]
From the [winget install learning](https://devblogs.microsoft.com/commandline/winget-install-learning/) blog post, it states `No scripts during install – something that we completely agreed with and don’t allow with MSIX` which possibly also includes pre-install as well rather than only post install.

**Comment by denelon** [comment]
@ItzLevvie is correct. This isn't something we're willing to consider at this time.
