### ISSUE TITLE
Winget shows eSpeak version as "Unknown" after updating it

### ISSUE THREAD

**Issue by Aerodymier** [microsoft/winget-cli#1389]
# Brief description of your issue
My eSpeak version was below the latest version. I updated it and now it shows my version as "Unknown". Tried updating again but didn't help.

# Steps to reproduce
- Install eSpeak
- Check updates from winget packet manager

# Expected behavior
It should show the version number correctly.

# Actual behavior
It shows version as "Unknown".

# Environment

```none
[winget --info]
Windows Package Manager version: v1.0.11694
Windows: Windows.Desktop version: v10.0.22000.160
Package: Microsoft.DesktopAppInstaller version: v1.15.11694.0

```

**Comment by ImJoakim** [comment]
The reason for this is because the version from `winget upgrade` or `winget list` relies on the information from the ARP (Add or Remove Programs) in the control panel.

The ideal solution is to request the publisher of the software to add a version to the installer.

![image](https://user-images.githubusercontent.com/52826317/130321290-f4a97933-4b98-4f42-a5a5-bf7d1faa3614.png)

**Comment by Aerodymier** [comment]
Ok thanks.
