### ISSUE TITLE
winget has incorrect capitalization in --help

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/winget-cli#139]
# Environment

```none
[winget --info]
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19619.1000
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Any other software?
```
n/a
# Steps to reproduce
winget --help

# Actual behavior
notice string reads: 
WinGet command line utility enables installing applications from the command line.
# Expected behavior
Should read
The winget command line utility enables installing applications from the command line.

**Comment by lmilunovic** [comment]
I'd like to contribute, and this issue seems like a good place to start. Seems as trivial as replacing values ins .resw files. 

What I would like to know is what is expected behavior in localisations for languages that do not have article such as "The" in English.

In some languages WinGet is first word in sentence, I guess it is still expected to be lowercase? 

For example, would this be expected behavior for Serbian locale:

> winget uslužni program komandne linije omogućava instaliranje aplikacija sa komandne linije.

It does seem a bit odd to see a line beginning with lowercase letter and fullstop at the end of it and, on the other side, that is the name of the program.

**Comment by denelon** [comment]
@lmilunovic I'm not an expert in any other languages. I would assume that we would be fine with a capital W for winget if it is the first word in a sentence for any language that starts with capital letters for the first word in a sentence.

**Comment by denelon** [comment]
We are using translation services to populate the resource files. I will see if I can help find a mechanism to contact them to improve the translations for the strings we're using.

**Comment by denelon** [comment]
The ask here is just to perform the en-US correction(s).
