### ISSUE TITLE
Repair an App that is behaving badly

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#148]
As a user I want to be able to repair my  app if it is not working correctly.

Client:
winget repair \<appname\>

Repair can only be done as a single apps as it doesn't seem to make sense to do this for all installed applications.

Most installers have a repair mode.  
1) add repair command to YAML spec.  this is probably the systemappid
2) search the ARP for the command and be able to call it.
3) this should also work for MSIX which are uwp store apps.

**Comment by Atemu** [comment]
The easiest way to repair something is usually to uninstall the package and install the same version again.  
An explicit repair operation might not be necessary.

**Comment by aycippo** [comment]
@denelon if it is not too much of an addition though, perhaps the addition of an --all or --tags options to the repair command? I think that would be useful to have in the of chances you are looking to repair your environment or a specific set of tools.

I would also think that since this would vary wildly between each package we would need to make sure that winget can understand and make the correct changes based on how it was installed. might be useful to consider a sort of package maintainer side doc/script/template that winget could follow in which they add this information.
