### ISSUE TITLE
Search and Install do not return the same results

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#1523]
# Brief description of your issue

# Steps to reproduce
run `winget search wireshark`
run `winget install wireshark`

# Expected behavior
If only one package is returned from search, only one package should be returned for install. Search and install should return the same available packages

# Actual behavior
```raw
PS C:\WINDOWS\system32> winget search wireshark
Name      Id                            Version Source
-------------------------------------------------------
Wireshark WiresharkFoundation.Wireshark 3.4.8.0 winget
PS C:\WINDOWS\system32> winget install wireshark
Multiple packages found matching input criteria. Please refine the input.
Name                  Id                            Source
-----------------------------------------------------------
Computer Networks One 9NC6N8L4T5WS                  msstore
Wireshark             WiresharkFoundation.Wireshark winget
```

# Environment

```none
PS C:\WINDOWS\system32> winget --info
Windows Package Manager v1.1.12653
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1237
Package: Microsoft.DesktopAppInstaller v1.16.12653.0
```

**Comment by jedieaston** [comment]
It looks like searches sent to a REST source look in specific fields when a search is ran for `winget install`, and those fields are not specified for `winget search`.

The body of the request for `winget search wireshark`:
```
{
   "Filters":[
      {
         "PackageMatchField":"Market",
         "RequestMatch":{
            "KeyWord":"US",
            "MatchType":"CaseInsensitive"
         }
      }
   ],
   "Query":{
      "KeyWord":"wireshark",
      "MatchType":"Substring"
   }
}
```
And the body of the request for `winget install wireshark`:

```

{
   "Filters":[
      {
         "PackageMatchField":"Market",
         "RequestMatch":{
            "KeyWord":"US",
            "MatchType":"CaseInsensitive"
         }
      }
   ],
   "Inclusions":[
      {
         "PackageMatchField":"PackageFamilyName",
         "RequestMatch":{
            "KeyWord":"wireshark",
            "MatchType":"Exact"
         }
      },
      {
         "PackageMatchField":"ProductCode",
         "RequestMatch":{
            "KeyWord":"wireshark",
            "MatchType":"Exact"
         }
      },
      {
         "PackageMatchField":"PackageIdentifier",
         "RequestMatch":{
            "KeyWord":"wireshark",
            "MatchType":"CaseInsensitive"
         }
      },
      {
         "PackageMatchField":"PackageName",
         "RequestMatch":{
            "KeyWord":"wireshark",
            "MatchType":"CaseInsensitive"
         }
      },
      {
         "PackageMatchField":"Moniker",
         "RequestMatch":{
            "KeyWord":"wireshark",
            "MatchType":"CaseInsensitive"
         }
      }
   ]
}
```

I'm guessing that something with the Store source (I don't know how much of the reference source they're using) makes it so it doesn't search anything if you don't specify a field.

**Comment by Masamune3210** [comment]
Definitely running into this, even specifying the id doesn't disambiguate it enough

![image](https://user-images.githubusercontent.com/1053504/135703711-9850e83e-b7fc-4319-a2dc-754a364446d2.png)

**Comment by Trenly** [comment]
> Definitely running into this, even specifying the id doesn't disambiguate it enough
> 
> ![image](https://user-images.githubusercontent.com/1053504/135703711-9850e83e-b7fc-4319-a2dc-754a364446d2.png)

Use the `—id` parameter specifier as a temporary workaround

**Comment by Jaifroid** [comment]
@Masamune3210 The ID could be case-sensitive. You wrote `gog.galaxy` whereas the ID is `GOG.Galaxy`. At least check if that might be an issue.

**Comment by Masamune3210** [comment]
From what I've seen install usually works with case-insensitivity but tried anyway, no dice

![image](https://user-images.githubusercontent.com/1053504/135731127-ee0cf05a-724d-4519-86ff-73455647a6e7.png)

**Comment by DirtySoc** [comment]
`winget install GOG.Galaxy -s winget` is a workaround also.

**Comment by peter-dolkens** [comment]
msstore is definitely causing issues here - you don't even get the same (incorrect) results between runs


```
C:\Users\peter>winget install Microsoft.VisualStudioCode
Multiple packages found matching input criteria. Please refine the input.
Name                         Id                         Source
---------------------------------------------------------------
Microsoft Whiteboard         9MSPC6MP8FM4               msstore
Microsoft Visual Studio Code Microsoft.VisualStudioCode winget

C:\Users\peter>winget install "Microsoft.VisualStudioCode"
Multiple packages found matching input criteria. Please refine the input.
Name                               Id                         Source
---------------------------------------------------------------------
Microsoft Wireless Display Adapter 9WZDNCRFJBB1               msstore
Microsoft Visual Studio Code       Microsoft.VisualStudioCode winget
```

**Comment by jedieaston** [comment]
If this is causing too many issues for you run `winget source remove msstore` to use the community repo only. If you want to try it again, run `winget source reset`.

**Comment by denelon** [comment]
I've covered a few tips in the [blog](https://devblogs.microsoft.com/commandline/windows-package-manager-1-1/) for Windows Package Manager 1.1.

**Comment by Jaifroid** [comment]
I actually think "search" and "install" should **not** return the same results. `winget search` should be a wide-ranging search that matches anything in product ID, moniker or package name. `winget install` should give precedence to any moniker that has been defined (and monikers should be unique). If the install request does not match a defined moniker, then it should attempt  to match by product id (this will give precedence to the winget repository, because msstore product IDs are random strings of letters).

On the other hand, `winget install` and `winget show` **should** return the same results, in my opinion. If I type `winget show kiwix`, I expect it to show details of the package that will install if I then type `winget install kiwix`. Unfortunately these commands are currently broken if a moniker is defined: see #1568.

**Comment by denelon** [comment]
I was just informed the deployment has completed.

**Comment by Jaifroid** [comment]
@denelon, why am I still getting this result when I run `winget install kiwix`? `kiwix` is a unique moniker, so I *expect* it to select the package based on the moniker. Monikers should have the highest priority, or else what are they for?

![image](https://user-images.githubusercontent.com/4304337/139748168-7fb7534a-6de8-426d-b6d5-24fd1e0bcfe2.png)

The other package listed here is completely random, as you can see from the result of `winget search kiwix` below. Why has it picked one WikiMed package from the msstore, and not, say, the Kiwix JS package from the store?

![image](https://user-images.githubusercontent.com/4304337/139748621-bca9e3f1-9415-4645-a311-09fb9ed536fd.png)

IMHO this issue is *not* fixed, and should be re-opened. I want to be able to tell my users that they can install my app very simply by typing `winget install kiwix`, as used to be the case. I should not expect them to have to remember obscure switches like `-s winget` added on the end.

**Comment by Masamune3210** [comment]
It's not a unique moniker if the word is in 7 different packages. That's like saying Java is unique even though it's in multiple package titles

**Comment by Jaifroid** [comment]
@Masamune3210 I beg to differ. We have the option of defining a moniker in the manifest, precisely to act as a shorthand. I publish all of the above packages, and I have given unique monikers to each of the packages in the winget repository. I used to be able to install each of them with these monikers:

`winget install kiwix` - Installed package Kiwix.KiwixJS
`winget install wikimed` - Installed package Kiwix.WikiMed
`winget install wikivoyage` - Installed package Kiwix.Wikivoyage

So, tell me, what is the moniker definition for in the manifest if it is not intended to act as a shorthand for a package ID? I repeat, monikers should have the highest priority in selecting a package. Tags are for searching. I have no quarrel with the *search* results. My problem is with the *install* (and *show*) results.

**Comment by denelon** [comment]
@Jaifroid the store source doesn't support moniker yet. This issue was about getting the "winget install" command to at least match consistently with results from "winget search". We're still working on additional improvements and customizations for behavior with other Issues here at GitHub for the client, and internally with the Microsoft Store source.

The moniker is intended to act as a shortcut. With two sources it's a bit more challenging. There is an order of precedence from the ID, Name,, and Moniker in the default "winget" source. We're looking at some additional heuristics to help when we get a result from more than one source. Since a moniker wouldn't be unique across multiple sources, we're looking to extend the behavior a bit further with preferences on source priority as well.

**Comment by Jaifroid** [comment]
@denelon, that would be very helpful. In the case of `winget install kiwix`, two packages are returned, one from the winget repository with a moniker of 'kiwix', and one from the msstore source, with no moniker. It seems "obvious" that a package from the winget source with a fully matching moniker should trump a package from the msstore source with only a partial match on the package name. But I know that coding these behaviours is complex, given the number of edge cases.
