### ISSUE TITLE
Regression: upgrade and import no longer print anything to the console.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-cli#1586]
# Brief description of your issue

After #1527, `winget upgrade --all` and `winget import` no longer print anything to the console if they have stuff to install.

# Steps to reproduce

1. Compile/install the latest master branch.
2. Use `wingetdev import <file>` or, if you have something outdated installed, `wingetdev upgrade --all`

# Expected behavior

It prints stuff to the console.

# Actual behavior

Except for momentary flashes of the spinner, nothing is printed. This happens in both the standard terminals (cmd.exe/powershell.exe) and Windows Terminal.

(I apologize if this is bad form, but I was working on a solution to #1566 when I noticed this. I stepped through it a few times but it wasn't obvious what was going wrong. I figured @hackean-msft might know before I did.)

https://user-images.githubusercontent.com/21368066/137143263-e6105053-6075-4f4e-9f07-e6bcebc51469.mp4

# Environment

```none
[winget --info]
Windows Package Manager version ??? (it identifies itself as v1.0.2, but it's the latest master branch)
Windows: Windows.Desktop version 22000.258
Package: Microsoft.DesktopAppInstaller version ???

Any other software?
```

**Comment by hackean-msft** [comment]
The main output stream  that controls all write operation is never cloned when the main context is cloned, this causes the output stream to be disabled upon the destruction of a subcontext(because we disable the output stream to prevent multiple background jobs from writing to the output stream, when user  force terminates). A pull request has been submitted to address the issue, allowing disabling of the output stream through forceful termination.
