### ISSUE TITLE
Group Policy - Force Package Updates

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-cli#1660]
### Description of the new feature / enhancement

Some administrators would like to enforce a policy requiring all software installed by Winget remain up to date. It would be nice to have a group policy setting to ensure the latest versions are always installed

There are a couple edge cases that I can think of, which may effect this sort of functionality -
- Pinned packages would have to have the behavior defined. Would GPO enforced upgrades override pinned packages? Is this something that would be another GPO? 
- Specific packages versus all packages. I can see a use case where admins may want to enforce that only certain packages stay up to date. There should likely be an option to have just select packages subject to the policy
- Minimum package versions. I could also see a use case where admins may want to force a minimum package version, but not necessarily the latest, for certain packages. Examples of this could be where they want to ensure everyone received a patch with a security update, but not force them to upgrade to the latest version
- What happens if a user does not have a package installed, or the version is unknown? Would the package be forced to be installed, or would the package update GPO only consider packages the user had installed
- What happens if the GPO defined version is greater than any version existing in the configured sources, or the package is unavailable in the configured sources? I would presume that specific entry would be ignored?

### Proposed technical implementation details

I think there are multiple ways this can be done. Here are just a few thoughts I had.

1. Hook into the source update with the list of installed packages. When the source is updated, check to see if the updates that were pulled down include any installed package. If there is a new version of the package available, install it, or queue it for installation before the next reboot. 
3. Periodically check the GPO for a list of the packages and minimum versions, compare these to the installed packages and versions, then upgrade the ones which require upgrading by policy
4. Run `winget upgrade --all` periodically or at user logon. Yes, I am aware that this can be done with a scheduled task group policy, but I think it would be cleaner if Winget had it's own policy for this

**Comment by jedieaston** [comment]
I like this idea, but isn't this what something like SCCM/Intune/SaltStack/Ansible is usually for? Intune is getting some winget integration sometime in 2022, maybe this should be part of that. (I know that doesn't help if you're still 100% on-prem, but it's something).

**Comment by Trenly** [comment]
> I like this idea, but isn't this what something like SCCM/Intune/SaltStack/Ansible is usually for? Intune is getting some winget integration sometime in 2022, maybe this should be part of that. (I know that doesn't help if you're still 100% on-prem, but it's something).

You’re right, those could potentially be used, but there is also a subset of users who use Windows 10 Pro for personal use or who manage small businesses that use Windows 10 Pro but do t have a need for some of those enterprise level solutions. There are probably other examples too where GPO would be more accessible

**Comment by denelon** [comment]
Group Policy can be a bit tricky. If a policy is configured, it must be honored, and the user must not be allowed to modify the state to conflict with the policy on their machine. For the Windows Package Manager, the policies are evaluated when the client and / or the COM API is run. There really isn't a notion of a policy for the Windows Package Manager that would cause it to be executed otherwise.

In theory, we could capture a source update for the PreIndexed package to cause a "winget upgrade --all" to be triggered, but the user could [Ctrl]+[c] the run. The user could also avoid running the Windows Package Manager to hold off as long as possible to avoid updates. We also need to think about the interaction when the user visits a Win32 App page in the Microsoft Store. We also don't receive a notice when a REST source has changes.

Policies shouldn't be built in a way they can conflict with each other. I would also be concerned about race conditions with respect to policies requiring packages be kept up to date vs. packages that are pinned.

I'm open to the suggestions here, there are just a large number of edge cases to make sure we get right before building and applying any new policies.

**Comment by jedieaston** [comment]
I think the only way to implement this would be a scheduled task, but that doesn't really require GPO options. (since we probably want to update all corp. installed apps on the system, therefore `winget upgrade --all`. I don't know that I'd want to require only a subset of installed apps be updated)

**Comment by Templar-jpg** [comment]
I am experimenting with a group policy scheduled task now and it is working. Someone please let me know if there is a better way of doing this.

1. I am copying a .cmd file with group policy to a folder on the workstations. The .cmd file looks like this:
CD "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.16.12653.0_x64__8wekyb3d8bbwe" 
AppInstallerCLI.exe upgrade --id=Google.Chrome -h --accept-package-agreements --accept-source-agreements
AppInstallerCLI.exe upgrade --id=Microsoft.Edge -h --accept-package-agreements --accept-source-agreements

2. The scheduled task is deployed using Create in group policy. The SYSTEM account runs the script daily. An 8 hour delay is used to randomize the scheduled task start time so that all workstations are not updating at once.

The pitfall of this is that when the version of Winget changes I must update the path in the script. I would just eliminate the script all together and put the --all command directly into the scheduled task but I don't want the Office update to run so that forces me to whitelist with a deployed script. Either way the path to AppInstallerCLI.exe needs to be updated either in the script or the scheduled task itself as it appears the winget command can't be ran by the SYSTEM account.

**Comment by rokejulianlockhart** [comment]
Why, @Trenly...?

**Comment by denelon** [comment]
I just add closed issues to the milestone in progress. I'd say it's more of a housekeeping behavior rather than an indication of intent. 

Other MDM providers as mentioned above really are a better place to handle this type of behavior. WinGet only evaluates policies when it is invoked. If it isn't run for an extended period of time, a policy wouldn't be applied.

**Comment by rokejulianlockhart** [comment]
Yeah, @denelon, although I don't believe that those are solutions for home users. Hence
> I know that doesn't help if you're still 100% on-prem
