### ISSUE TITLE
Support installing packages that require additional files

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-cli#1681]
### Description of the new feature / enhancement

Some packages like Orca (Windows Installer Table Editor) has an MSI installer but needs additional CAB files.
![image](https://user-images.githubusercontent.com/83997633/140611973-45d344c3-4eaf-4165-92df-05c7d55a15ed.png)

We just need to download the CAB files in the directory where the MSI installer is downloaded.

### Proposed technical implementation details

- Changes in the manifest schema.
   - A new field inside PackageDependencies can be introduced like:
     ```
     PackageDependencies:
     - DependencyFileUrl: <url>
       DependencyFileSha256: <hash>
     ```
     **Since v1.1 schema is not released yet, can I expect this to be there?**
- winget-cli would download all the files in the directory where the installer is downloaded and run the installer normally.

**Comment by vedantmgoyal2009** [comment]
Changes in validation pipeline would also be required to validate the `DependencyFileUrl` and `DependencyFileHash`.

**Comment by jedieaston** [comment]
I know this violates "winget takes the world as it is, not as we'd like it to be" but I'd rather ask the ISV to bundle it in a zip or inside their installer. Automatically modifying manifests and all of these `DependencyFileUrls` and keeping them in sync will be absolutely insane (from a community repo perspective).

Orca is bundled as part of the Windows SDK (`Microsoft.WindowsSDK`), for that specific case maybe installing the whole SDK makes more sense? The reason you're missing cab files is probably because the Orca msi file is supposed to be ran from the Windows SDK install media (or folder, or whatever).

**Comment by denelon** [comment]
For this one, I am inclined to agree with @jedieaston. I'll leave this feature open so we can see if we run into this problem on a larger scale. Dependency support is already quite complex. I'll bring this up in the next design review. It is too late to get into the 1.1 schema, but we will discuss this for 1.2.

**Comment by joel0** [comment]
Having a dependency file would be useful for the package I'm working on.  The Microsoft Keyboard Layout Creator generates msi files that require a subdirectory with a dll.  https://github.com/workman-layout/Workman/tree/53a8e71b65700a26916981d4ebef0ce0bae503f6/windows/installer/workman-us

After #140 is implemented, I could have the package download the whole Workman repository as a zip to get the installer and dll, but there would still be benefit to only downloading the 2 files needed if DependencyFileUrl gets added.
