### ISSUE TITLE
Make the text for the Microsoft Store disclaimer yellow.

### ISSUE THREAD

**Issue by jedieaston** [microsoft/winget-cli#1682]
### Description of the new feature / enhancement

There's been a little confusion (https://github.com/microsoft/winget-pkgs/issues/34313, but I've seen it other places too) about the difference between the msstore source and the winget source from a user perspective. 

I think part of this is because the msstore source spews 30 lines to stdout which nobody slows down to read. However, the second line, `This package is provided through Microsoft Store. winget may need to acquire the package from Microsoft Store on behalf of the current user.` is really important for users when they want to know where to ask questions.

I think this text should be made yellow so that it pops out to the user. (If we have agreement about this, I can make the PR. Literally a one line, five second change.)

### Proposed technical implementation details

Change `context.Reporter.Info()` to `context.Reporter.Warn()` [here](https://github.com/microsoft/winget-cli/blob/467adfa34ede4cc7291022a28eef3b9a5d8c69d9/src/AppInstallerCLICore/Workflows/InstallFlow.cpp#L126).

**Comment by denelon** [comment]
I've been looking at accessibility. I'm not sure if we're using colors as well as we could. Does bold standout well enough? I think contrasts well enough with black or blue backgrounds, but other terminal background color schemes might not work so well. I also think we need to change the string from "winget..." to "The Windows Package Manager..."

**Comment by jedieaston** [comment]
Bold would also work. The thing about colors is that you can override them (or disable them) in most terminals, for example in Windows Terminal my yellow is changed to red (as an example): 
![image](https://user-images.githubusercontent.com/21368066/140771201-79fd465f-f759-4e56-8093-8c08fcdcf294.png)

I don't know if there's any good documentation about a11y in command line apps, as the assumption is "it's just text", and the colors are not essential to functionality.

**Comment by denelon** [comment]
Yes, we're working though several a11y issues. There are also differences between the Windows Terminal palette and the PowerShell palette. We have some internal guidance with respect to contrast. Rather than selecting colors, the guidance seems to be heading towards either using text formatting, or a combination of text and color (I'm not a fan of this one as we would need some kind of library to make sure sufficient contrast exists between colors). Something like a "WARNING" or "ERROR" prefix in front of the text. If you don't mind, let's give bold a try and see if that helps. Otherwise we might need to try something else if we get any other feedback.

**Comment by denelon** [comment]
I've also seen some examples where all warnings are prepended with "WARNING:" and all errors are prepended with "ERROR:". I'm looping back to see if that is a best practice or not. As we move to more behavior around the complexities with upgrading or importing packages (especially when dependencies are involved), I believe this will become more important to get right.
