### ISSUE TITLE
Provide a way to install unix tools

### ISSUE THREAD

**Issue by keenbowl3009** [microsoft/winget-cli#1695]
### Description of the new feature / enhancement

Winget is a command line package manager tool. 

However, it is literally the worst package manager tool that exists. 

As it currently stands, it is IMPOSSIBLE to create a package to install unix command line tools, such as touch, awk, grep, etc, in my machine. 

A great simple implementation of these tools is for example [BusyBox](https://busybox.net/). 

However, since winget does not support one of the simplest use case which is "unzip these files, and make them available in path". 

Winget is also yet another half-assed broken poorly designed windows alternative of a tool that creates more problems than it solves. 

Winget was quite literally STOLEN from AppGet, and is currently an inferior version of Scoop at https://github.com/ScoopInstaller/Scoop/issues/3634

**Comment by Masamune3210** [comment]
Was this issue made in bad faith? 

Zip support is actively being worked on. 

The idea of stealing a package manager implementation isn't a thing considering that literally everyone either copies apt or pacman.

I'm not sure what the point of this issue is other than to intentionally try to provoke people

**Comment by vedantmgoyal2009** [comment]
WinGet is a package manager that will take over choco and scoop in the coming time. Never underestimate it.

**Comment by JennyStig** [comment]
Of course WinGet will take over choco and scoop. 
WinGet is baked with windows, and aggressively marketed by msft. 

The difference, though, is that the scoop community, for one, is organic: people will maintain packages there because they have their own opinion of the right way of doing things. 

Winget on the other hand is completely unopinionated. It encourages developers and packages to use the most convoluted and user hostile proprietary tools as possible.

**Comment by Masamune3210** [comment]
...it really doesnt. how is yaml a proprietary or hostile tool. that is literally all that's needed to add a program to the database, and anything else is up to the user. what exactly is convoluted about it?

**Comment by CharlotteEm** [comment]
> that is literally all that's needed to add a program to the database, and anything else is up to the user

How can I create a installer for a single binary? All I need is to make it available on my path so I can call it with the command line.

**Comment by Masamune3210** [comment]
You dont, but hopefully will be able to soon. support is being actively hammered out for archives and portable binaries

**Comment by keenbowl3009** [comment]
> support is being actively hammered out for archives and portable binaries

Pretty soon when, exactly?

**Comment by keenbowl3009** [comment]
I do not understand why my issue was closed without mentioning other issues that exist, and with no justification from microsoft.

**Comment by Masamune3210** [comment]
When the devs get everything hammered out, it will be announced just like every other feature announcement and release

The issue was closed likely because your issue smells strongly of nothing more than a bad-faith argument. Its very obvious from the volume of commits and issues that things are still being worked on, and multiple issues have been opened and answered on the issue of portable apps.

**Comment by keenbowl3009** [comment]
> The idea of stealing a package manager implementation isn't a thing considering that literally everyone either copies apt or pacman.

Is this an official quote, on the record, that microsoft stole appget?

**Comment by Masamune3210** [comment]
No, because A: I am not a Microsoft employee, and B: don't care enough to argue farther with you, as you seem to not be even listening

**Comment by mathemaphysics** [comment]
Being a thorough and exclusive user of Ubuntu and loving it, I have to say I love Winget. It brings the convenience of apt-get to Windows.

Very much appreciated. Awesome work.

**Comment by FeignMan** [comment]
@keenbowl3009 You do understand that the devs working at Microsoft are also people right? They react the same way when you shit on their work. In fact try doing this on any open source repo and the maintainer will probably give you a dose of 'advice' before closing your issue.

Anyhow, I love the work being done here - and I personally use scoop. It's not about what's best - it's about having a variety of options, the freedom to choose, and providing a default solution for Windows out of the box. Love it, keep up the good work.
