### ISSUE TITLE
Blender update reports "multiple packages found"

### ISSUE THREAD

**Issue by xarthurx** [microsoft/winget-cli#1778]
```
>winget upgrade --id BlenderFoundation.Blender

Multiple installed packages found matching input criteria. Please refine the input.
Name    Id
----------------------------------------------
Blender BlenderFoundation.Blender
blender {8E411BEA-E05E-4E73-B9D3-A89A3084D67D}
```

and `winget update --all` won't update the software either.

**Comment by xarthurx** [comment]
But, the software IS updated when using the `update --all` option, though when doing `winget update`, it still shows the software is not updated...

Not sure why.

**Comment by denelon** [comment]
This appears to be the case where either the package is installed "side by side" rather than upgrading the package in place, or the upgrade doesn't properly modify the entries in Apps & Features. This "loop" is unfortunately fairly common when the Windows Package Manager doesn't have sufficient metadata in the manifest to make an exact match to exactly one instance of the package being installed on the system. We're working on improving the matching and allowing multiple entries in the manifest for the metadata reported to Apps & Features.

**Comment by denelon** [comment]
We've been working on the side-by-side scenarios. You could try the latest release and enable the experimental feature on:
* https://github.com/microsoft/winget-cli/releases/tag/v1.8.924-preview

Please provide feedback at:
* https://github.com/microsoft/winget-cli/discussions/4281

**Comment by denelon** [comment]
Is this still a problem on WinGet 1.8?
