### ISSUE TITLE
Winget will not run no option to uninstall App Installer

### ISSUE THREAD

**Issue by Lewiscowles1986** [microsoft/winget-cli#1840]
### Brief description of your issue

Really very annoyingly this does not seem to be in my PATH.

![image](https://user-images.githubusercontent.com/2605791/148668261-0408e6c4-e8a4-4149-8ff4-42a1a019fa29.png)

Windows store is logged in. And reports the app being installed; as well as compatible with my PC.

![image](https://user-images.githubusercontent.com/2605791/148668267-ea302042-89f5-490c-bce1-be4ea9df1a3a.png)
 
Powershell in the screenshot is in administrator mode.

Please just tell me where this heap of trash is supposed to be installed so I can manually add it to my path.

### Steps to reproduce

unknown how system got into this state.

### Expected behavior

type winget; at least finds the damn executable

### Actual behavior

Pictured. Powershell cannot find the executable

### Environment

```shell
N/A (Can't run winget)
```

**Comment by Masamune3210** [comment]
If its such a heap of trash, then just uninstall it and leave, its not hard. Why are you asking for help for something you obviously don't want to use anyway

**Comment by Lewiscowles1986** [comment]
It has no uninstall button

**Comment by Masamune3210** [comment]
Because its a system app, you didnt install the app, you installed a update. If you don't use it just ignore it

**Comment by Lewiscowles1986** [comment]
So uninstall it is the first advice. Then I can't uninstall it, and should ignore it like inert software that just sits on the machine... 

Please let someone else respond to the ticket, or close it, or leave it. You're making this worse, you haven't answered the question about where the executable should be. You've provided nothing.

You seem to have read 4 words which you've taken exception to. You've just let me know that this has been installed on my machine without my knowledge and is hidden from my path. That is malware behavior; I only ever add to my path, I don't remove from it. 

It shouldn't take very much to imagine why someone might be annoyed. This isn't some 15 year old school kid project, or  a bunch of hobbyists. It's under the Microsoft org, a billion dollar company that has malignantly infested the PC market for the past 30 years.

If something has been installed on computers, then it should damn well work or have the path documented!

**Comment by ItzLevvie** [comment]
> So uninstall it is the first advice.

There's no easy way for you to do that.

Any other way, such as taking over `C:\Program Files\WindowsApps`, is likely to put your OS in a broken state.

If you do it correctly then you'll likely not run into any issues, but a lot of the posts in various subreddits for Windows are about people messing up their permissions for the `C:\Program Files\WindowsApps` folder and are unable to launch any Microsoft Store apps as a result of this.

> Then I can't uninstall it, and should ignore it like inert software that just sits on the machine...

If you're unable to uninstall App Installer via `Get-AppxPackage -Name Microsoft.DesktopAppInstaller | Remove-AppxPackage` in Windows PowerShell then you will simply have to leave it alone unless the Windows Package Manager (WinGet) engineering team has a latest App Installer build laying around without WinGet pre-built into it which you can reinstall over your current App Installer build.

> You're making this worse, you haven't answered the question about where the executable should be.

On your device, there's supposed to be a `winget.exe` file in `%LOCALAPPDATA%\Microsoft\WindowsApps` which is a reparse point (similar to a shortcut) for `C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3411.0_x64__8wekyb3d8bbwe\winget.exe`.

You could also put `C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.3411.0_x64__8wekyb3d8bbwe` into your `PATH` but that's not recommended as any updates to App Installer you receive from the Microsoft Store will break that `PATH` which is why there should be a `winget.exe` in `%LOCALAPPDATA%\Microsoft\WindowsApps`.

> Confirmed I've not installed this, and it is unlikely a user has. You've just let me know that this has been installed on a machine without the owner knowledge and is hidden from their path. That is malware behavior.

App Installer has been pre-installed into Windows 10—and now Windows 11 as well—for several years now and is pre-installed into Windows to easily allow you to install any `.appxbundle` and `.msixbundle` packages in the form of a user-friendly GUI which will also automatically install any dependencies missing from your device if you do that:
![image](https://user-images.githubusercontent.com/11600822/148687672-61a0aea3-1572-4701-9979-16505bb60ad9.png)

Windows Package Manager (WinGet) is part of App Installer, however, it's currently not part of a clean installation of Windows; and one of the ways to receive Windows Package Manager (WinGet) is by updating App Installer from the Microsoft Store.

It's possible to downgrade your App Installer build which doesn't have Windows Package Manager (WinGet) pre-built into it, but you're more likely to run into security vulnerabilities, such as https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-43890, which is solved in https://github.com/microsoft/winget-cli/releases/tag/v1.2.3411-preview.

Also, regarding the automated software installs and automated software updates on your device without your consent. This is essentially what the Microsoft Software License Terms (EULA) says:
- **Updates** = The software periodically checks for system and app updates, and downloads and installs them for you. You may obtain updates only from Microsoft or authorized sources, and Microsoft may need to update your system to provide you with those updates. **_By accepting this agreement or using the software, you agree to receive these types of automatic updates without any additional notice_.**

> I only ever add to paths of machines I use, I don't remove from the PATH.

For some applications on Windows that's a bit unnecessary, as the installer will take care of that for you automatically without needed your user interaction.

For example: If you wanted to install [Git for Windows](https://github.com/git-for-windows/git), it'll automatically do that for you.

One disadvantage of this is that it can sometimes break your `PATH` when an installer adds it to your `PATH`.

For example: An installer may add unwanted semi-colons or unwanted special characters to your `PATH` which will break something in said `PATH`. This was the case for some people who reported to have issues with the Windows Package Manager (WinGet).

So please make sure to double-check your `PATH` to make sure that it isn't the case:
![image](https://user-images.githubusercontent.com/11600822/148689288-adedb17c-dade-484e-a7bf-e9fca4949489.png)
![image](https://user-images.githubusercontent.com/11600822/148689297-2d2f012d-8335-425b-b2cb-f52a34b4416d.png)
![image](https://user-images.githubusercontent.com/11600822/148689301-12d8c83a-de7e-4778-875f-3230990d30f2.png)

> If something has been installed on computers, then it should damn well work or have the path documented!

If you're running a consumer version of Windows, it should already be in your `PATH`.

In this case, `%LOCALAPPDATA%\Microsoft\WindowsApps` should be in your `PATH`.

`PATH` issues are also documented over at https://github.com/microsoft/winget-cli/blob/master/doc/troubleshooting/README.md#common-issues.

For curiosity, here's what my virtual machine looks like, with a working Windows Package Manager (WinGet):
1) Screenshot that shows `%LOCALAPPDATA%\Microsoft\WindowsApps` in my `PATH`
- ![image](https://user-images.githubusercontent.com/11600822/148687248-86b7e175-e95c-489f-8157-b974ac5239f5.png)
2) Notice how `winget.exe` is present:
- ![image](https://user-images.githubusercontent.com/11600822/148687312-84cd22b0-37ba-4b44-b283-b9c2bc649c1f.png)
3) `Get-AppxPackage -Name Microsoft.DesktopAppInstaller`:
- ![image](https://user-images.githubusercontent.com/11600822/148687338-01d7fc35-9247-47c7-ad4e-547b291259fd.png)
4) `winget --info`:
- ![image](https://user-images.githubusercontent.com/11600822/148688506-0d00fbec-cbe3-4a89-a654-29ee04df499b.png)

**Comment by Lewiscowles1986** [comment]
Thank you @ItzLevvie what wonderful thorough documentation. You are so kind and helpful, I apologize for my bad behavior earlier. I'll close this out now as it gives me lots of information. I Had tried https://github.com/microsoft/winget-cli/tree/master/doc/troubleshooting but this looks like there are a few things I'd not tried, including removing (which hopefully will let me re-install and get to clean).

**Comment by Lewiscowles1986** [comment]
`%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe` was found... Strangely this is also where my python is, which works.

You were right about the WindowsApps in program files. Likely some DRM. I was trying to make sense of the various app folders that contained the symlink'ish thing pointing at the real executable.

Success!
![image](https://user-images.githubusercontent.com/2605791/148694510-5c33ed62-209a-406d-b391-c168f9a85d5c.png)
