### ISSUE TITLE
Download speed is slower than manually download.

### ISSUE THREAD

**Issue by biswasmoheshwar** [microsoft/winget-cli#1860]
### Brief description of your issue

Download speed is slower than manually download.

### Steps to reproduce

winget install/upgrade something

### Expected behavior

The speed would be same.

### Actual behavior

The speed is far slower. Around 30kb/s.

### Environment

```shell
Windows Package Manager v1.1.12653
Windows: Windows.Desktop v10.0.22000.376
Package: Microsoft.DesktopAppInstaller v1.16.12653.0
```

**Comment by biswasmoheshwar** [comment]
Fixed

**Comment by hueldoeu** [comment]
i am loading qBittorrent.qBittorrent and it's very slow while libreoffice is fast. i think it depends on the servers.

**Comment by Its-Satyajit** [comment]
> "network": { "downloader": "do" }, "do" downloader is even better than winget

I tried both "do" & "wininet" just now, in my case wininet is better I am getting 3-5 times more Downloding sepeed with it.

**Comment by Dev123456689** [comment]
> "network": { "downloader": "do" }, in my case **"do"** is relatively **faster** than **"wininet"**. 😊

I tested both **"wininet"** and **"do"**, and yes **"do"** is relatively faster than **"wininet"** but it's still way slower than normal download speed I get when downloading manually.

**Comment by lazee486** [comment]
just checking - winget probably uses windows background intelligent transfer service (BITS)  which would slow down the transfer if the pc is in use...  also allows for peer to peer transfer of files. 
maybe try 
winget install -e --id Microsoft.bitsmanager
and see if theres activity without the json change

**Comment by hueldoeu** [comment]
> Problem still persists years later.

not on my watch. download speed is fast enough for every of my packages. and unigetUI is a very nicee piece of software.

**Comment by 1nstntKaRma** [comment]
About one year later...

**Issue Fixed! @ all systems tested** 💯👊🏼🔥  

-------------------------------------------------------------------------------------------------------------

`netsh int tcp set global autotuninglevel=normal`



- Systems that would reach high bandwidth when checking @ SpeedTest.net (Even 700mbps ++)
- But when used through a Terminal would get around 1mbps ~ 4mbps
- Would only happen in Wi-Fi mode [for me]
- When switched to Wired Connection - no issue [for me]

Issue was actually related to Individual Network Adapter TCP settings, explaining how connecting through a wired connection temporarily "Solved" the problem. 
Different Network Adapter -> Different Setting = no bandwidth restrictions.

`autotuninglevel=normal` 
Allows the TCP stack to dynamically adjust the size of the receive window based on network conditions. 
This optimizes data flow, reducing bottlenecks caused by fixed or small window sizes. 
**In high-speed or long-distance connections, this adjustment can drastically improve bandwidth utilization, increasing speed even by x100 compared to a restrictive setting.**

+ The fix also seems to **drastically** improve browser (Chrome tested) download speeds as well.
(I tried a lot of stuff, if this doesn't fix your problem feel free to contact me)

**Comment by MichelZ** [comment]
> Have you tried disabling Delivery Optimization and using the "normal" downloader? It's possible something gummed up on your machine that is making DO act funny.
> 
>     1. Run `winget settings`.
> 
>     2. In the JSON block that appears, add
> 
> 
> ```
> "network": {
>     "downloader": "wininet"
> }
> ```
> 
> Now try a `winget install` and see if you have better results.

Argh. Why does every program try to re-invent the wheel. Just download files normally, damit.
Thank you very much for the tip!

**Comment by myudak** [comment]
still SLOW, even sometimes stuck, bro scoop literally more reliable than this, at least with the speed part

**Comment by fazzaan** [comment]
This is not fixed. I changed the json settings to 'wininet' and it is *substantially* faster now. The original download speed was a fraction of my connection speed. A 1.23 GB update file took 30 seconds to download just 120MB... I cancelled it, changed from 'do' to 'wininet' and the whole file then downloaded in under 30 seconds.
