### ISSUE TITLE
Following the closed issue #1824, apparently not resolved : [Microsoft.EdgeWebView2Runtime]Unable to install, error code 2147748098

### ISSUE THREAD

**Issue by Grimst** [microsoft/winget-cli#1883]
### Brief description of your issue

Hello,
i have the same issue right now

winget upgrade Microsoft.EdgeWebView2Runtime

Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 97.0.1072.76
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...

**Installer failed with exit code: 2147748098**

winget --info

Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1469
Package: Microsoft.DesktopAppInstaller v1.17.3411.0

Cheers
Steve

### Steps to reproduce

winget upgrade Microsoft.EdgeWebView2Runtime

### Expected behavior

anything else than a : Installer failed with exit code: 2147748098 ...

### Actual behavior

Installer failed with exit code: 2147748098

### Environment

```shell
winget --info

Windows Package Manager (Preview) v1.2.3411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1469
Package: Microsoft.DesktopAppInstaller v1.17.3411.0
```

**Comment by jedieaston** [comment]
The [Edge team was confused why I had to put that key into the manifest](https://github.com/microsoft/winget-pkgs/pull/39467#issuecomment-1020705905), so I removed it in the latest update to Edge WebView2. Turns out that was a bad idea :(

Anyway, it will be hopefully resolved once https://github.com/microsoft/winget-pkgs/pull/43955 is merged. After that manifest is merged, can you try again?

**Comment by vedantmgoyal2009** [comment]
Well, @jedieaston, I was thinking of removing previous versions of browsers since most of them auto-update themself in the background. (atleast we can think about beta/dev channels of brave)

**Comment by jedieaston** [comment]
If the download links stay around there’s no reason to remove them IMO, if someone wants to download an old browser winget should be able to do it. Maybe something to open a discussion about.

**Comment by Grimst** [comment]
Hello jedieaston,

I appologize ! i have just noticed your modification is not include in the v1.2.3411-preview of winget-cli i have installed and in which i have this current problem.
Sorry guys, I should have done it better !
i close this issue

Steve

**Comment by Juglugs** [comment]
So how do we (the users) fix this issue? I keep getting it

**Comment by jedieaston** [comment]
The issue wasn't resolved by that PR so I rolled it back. Sorry. 

We're waiting on either the Edge team to fix their installer or for https://github.com/microsoft/winget-cli/issues/1885 to be resolved (that will take a *long* time, so hopefully the first one)

**Comment by OfficialEsco** [comment]
Ok since there are a few issues around this, `Microsoft.EdgeWebView2Runtime` requires to be installed with terminal ran as Administrator because it does not self elevate.
This will be resolved once winget-cli supports the field `ElevationRequirement: elevationRequired`.

as user: 
```
PS M:\> winget install Microsoft.EdgeWebView2Runtime
Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 98.0.1108.43
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/257e16c7-6b27-41bc-b212-64d0a9418970/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
  ██████████████████████████████   116 MB /  116 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 2147748098
```

Upgrade with administrator and without the uninstallPrevious switch
```
PS M:\> winget upgrade Microsoft.EdgeWebView2Runtime
Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 98.0.1108.43
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Successfully installed
```

Additional answer to the ones who still see `Microsoft.EdgeWebView2Runtime` as a available upgrade; check if you have 2 different `Microsoft Edge WebView2 Runtime`'s installed (could be another architecture)

Related issues: https://github.com/microsoft/winget-cli/issues/1883, https://github.com/microsoft/winget-cli/issues/1824, https://github.com/microsoft/winget-cli/issues/1904, https://github.com/microsoft/winget-cli/issues/1873, https://github.com/microsoft/winget-pkgs/discussions/44812

**Comment by hubertsvk** [comment]
PS C:\Users\user> winget upgrade --all
Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 98.0.1108.55
Found  [Microsoft.EdgeWebView2Runtime] Version 98.0.1108.55
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/cae1821c-be52-4d6b-8409-83fa73fc5a73/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
  ██████████████████████████████   116 MB /  116 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 2147748098

**Comment by OfficialEsco** [comment]
Again, run Powershell or Windows Terminal as Administrator.
