### ISSUE TITLE
winget doesn't recognizes not the installed version of Toggl

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/winget-cli#1884]
### Brief description of your issue

winget doesn't recognizes the version of Toggl.TogglDesktop and winget upgrade --all reinstall it every time.

### Steps to reproduce

```PowerShell
PS C:\Users\admin> winget upgrade
Name        ID                 Version Verfügbar Quelle
-------------------------------------------------------
Toggl Track Toggl.TogglDesktop Unknown 7.5.363   winget
1 Aktualisierungen verfügbar.
```

### Expected behavior

winget should recognizes the version of Toggl.TogglDesktop

### Actual behavior

winget doesn't recognizes the version of Toggl.TogglDesktop

### Environment

```shell
PS C:\Users\dago.PRISMA> winget --info
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19044.1466
Paket: Microsoft.DesktopAppInstaller v1.16.13405.0
```

**Comment by jedieaston** [comment]
The infinite reinstall upgrade issue was resolved in https://github.com/microsoft/winget-cli/pull/1765, although I don't know when it will be in a release.

This is caused by the developer not putting a version number in the Add and Remove Programs table. To make this a better experience, if you can reach out to the developer and ask them to add their version number to the table it would fix the problem cleanly. There will probably eventually be mitigations for this in winget's local package tracking db, but the best fix is on the developer's side.

https://github.com/microsoft/winget-cli/issues/1692 and https://github.com/microsoft/winget-cli/issues/1439 are issues tracking this.

**Comment by DanielGoehler** [comment]
Ok, thanks!
