### ISSUE TITLE
Discord does not install

### ISSUE THREAD

**Issue by revanmj** [microsoft/winget-cli#189]
# Brief description of your issue
When trying to install Discord via winget, installer throws an error about lack of permission to copy file. Doesn't matter if this is done via Windows Terminal launched as admin or not (in the latter case, error left in console is different and only second error from attached screenshot is displayed).

![error](https://user-images.githubusercontent.com/1777618/82355556-a65dd200-9a02-11ea-9cd7-a74069151ccd.png)

# Steps to reproduce
1. Launch Windows Terminal as admin
2. Issue `winget install Discord` command

# Expected behavior
Discord installs properly

# Actual behavior
Installation fails

# Environment
```
Windows Package Manager v0.1.41331
Windows: Windows.Desktop v10.0.19041.264
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by revanmj** [comment]
Console output:

1. When run as admin:
```
C:\Users\revanmj>winget install Discord
Found Discord [Discord.Discord]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.discordapp.net/apps/win/0.0.306/DiscordSetup.exe
  ██████████████████████████████  59.7 MB / 59.7 MB
Successfully verified installer hash
Installing ...
Successfully installed!
An unexpected error occurred while executing the command:
remove: Access Denied: "C:\Users\revanmj\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet\Discord.Discord.0.0.306.exe"
```

2. When run as normal user:
```
C:\Users\revanmj>winget install Discord
Found Discord [Discord.Discord]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.discordapp.net/apps/win/0.0.306/DiscordSetup.exe
  ██████████████████████████████  59.7 MB / 59.7 MB
Successfully verified installer hash
Installing ...
Installer failed with exit code: 4294967295
```

**Comment by JohnMcPMS** [comment]
The admin install is trying to remove the downloaded installer after a success.  It should be installed in that case, but we need to fix the timing issue there.

As a normal user, that is a very unhelpful error code that they are returning, but I expect that they require Admin to install since they are writing to ProgramData.

**Comment by revanmj** [comment]
There is no shortcut in Start Menu or entry in Add/Remove Apps panel, so there winget wrongly assumes that install was successfull.

**Comment by aditya-giri** [comment]
+1, a bunch of apps all failed to install for me with this same error.

**Comment by jefferai** [comment]
My issue got closed as a duplicate but I get "Access Denied" and it's definitely not installed. Seems like a lot of different behaviors are being lumped in as duplicates of this, is it all the same underlying cause?

**Comment by Bartmax** [comment]
I get access denied as https://github.com/microsoft/winget-pkgs/issues/1367 but installation was successful

**Comment by hacker1024** [comment]
I get the same issue with `Telegram.TelegramDesktop` and `Axosoft.GitKraken`. Should this issue be renamed with a broader description?

**Comment by AmitKKhanchandani** [comment]
Same issue with `Atlassian.Sourcetree`

**Comment by hacker1024** [comment]
I reckon there've been no fixes from Microsoft because `Git.Git` also doesn't install.

**Comment by beppler** [comment]
I have the same problema with Git.
It works if my user is administrator and I run winget in an elevated prompt.
If my user is a normal account even if I run an elevated prompt (using an administrator account) it fails.

[Git.Git.2.28.0.log](https://github.com/microsoft/winget-cli/files/4994799/Git.Git.2.28.0.log)

**Comment by megamorf** [comment]
@beppler are you really sure that winget's parent process was started with elevated privileges? In your log it says:

```
 User privileges: None
```

Which implies that your process was only ran with the standard user access token. What's your UAC configuration?

**Comment by beppler** [comment]
Yes, I made the wrong test, If I my account is not an administrator and I start an elevated prompt (my UAC configuration is default), after type my credentials and try to run winget I'm getting the following message:

```
PS C:\Users\adm-beppler> winget
ResourceUnavailable: Program 'winget.exe' failed to run: The file cannot be accessed by the system.At line:1 char:1
+ winget
+ ~~~~~~.
```

If I try to install Git using the normal account the error is that in the log I sent.

If I switch user to the administrative account (MPS\adm-beppler), I can install it (after open an administrative prompt).

**Comment by denelon** [comment]
This looks like it can be addressed when we implement #149 User vs. System.

**Comment by denelon** [comment]
This looks like the installer is launching a separate process to install. We don't yet track the installers in these kinds of situations. This appear to be related to the installers. I'll mark this issue as "Area-External" as we work through the right kind of a Feature that might resolve this issue.

**Comment by jefer94** [comment]
But if `winget install` don't yet track the installers, we can't use `winget install`, also i need say that `IT Policies` is one feature of windows, he install `Discord` and appear one `IT Policies` error, I install `Postman` and appear the same error, we should look how why `IT Policies` don't support `winget` to solved this issue

**Comment by denelon** [comment]
@jefer94 the Windows Package Manager tracks the packages installed by "packageIdentifier" from the community repository, or the source the package manifest originated from.

This issue is really about the mechanics of some specific installers. When the winget.exe client begins to install a package, it kicks off a child process and watches the return codes from that process to determine if the install completed, or threw an exception. In the case of Discord, it appears the installer (executed by the process winget.exe initiated) launches it's own child process, and the one we launched finishes with a successful result.

As the actual process that is running the install (executed by the installer process) isn't the one that was launched by winget.exe, We aren't receiving return codes from that other process to determine if there was a successful result or not.

The Windows Package Manager in process "A" launches process "B" to install Discord.
Discord's installer in process "B" launches process "C" to perform the install.
Process "B" exits with a success result.
The Windows Package Manager in process "A" receives the success result and reports success.
Process "C" encounters a failure, and no return code is provided to process "A".

**Comment by jefer94** [comment]
Maybe the solution should be use packages instead of installers, we just need copy any package manager that it work, or specify one new installer standard that support winget. Also winget should support install package in other hard drive. But you think that exist a lot of package manager in the actually, and all work perfectly, exist one lot of behavior that it should be the behavior of winget, also you think if one user want to install 3 diferents packages and each installation fail, this user will not use winget, because it's not work

**Comment by denelon** [comment]
I was just able to install Discord. The shortcut also showed up in the Windows menu, and the program launched correctly.
![Discord](https://user-images.githubusercontent.com/61799811/116584425-2f94ae80-a8cc-11eb-99f4-fe571b4412b6.png)

Windows Package Manager v0.3.11102 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.928
Package: Microsoft.DesktopAppInstaller v1.11.11102.0

**Comment by jefer94** [comment]
![Capture](https://user-images.githubusercontent.com/3018142/116618037-2b848300-a904-11eb-89eb-4b98db5d7112.PNG)

**Comment by jefer94** [comment]
![Capture](https://user-images.githubusercontent.com/3018142/116618124-47882480-a904-11eb-9013-6de8640a5826.PNG)

**Comment by denelon** [comment]
@jefer94 did you run this install in "user" mode or "administrator"?
I believe I receive a UAC prompt when I installed postman last in user mode.

If there are IT Policies restricting packages from installing to C:\ProgramData\ then the Postman installer would be denied access.

**Comment by jefer94** [comment]
it show the same
![Capture](https://user-images.githubusercontent.com/3018142/116620612-ae5b0d00-a907-11eb-9bca-2f11f3b1261d.PNG)

**Comment by electronic-dk** [comment]
I wasn't able to install discord via winget from either user or an elevated prompt. Unlike git, which at least worked from an elevated prompt. Although I'm getting a different error.
![image](https://user-images.githubusercontent.com/2945527/119832728-1e5cb300-bf07-11eb-98fa-235c3f868b3b.png)

**Comment by intel352** [comment]
I get the IT policy error as well. Running winget via non-admin prompt, Discord errors with a reference to ProgramData path.
Winget correctly reports the install failed: `Installer failed with exit code: 4294967295`

**Comment by smabuk** [comment]
I'm seeing the same behaviour in winget v1.0.11451 trying to install GitHub.GitHubDesktop (2.8.2) from an elevated prompt.
winget sees the result as successful, but the windowed app shows 
Installation has failed - Unable to write to "C:\ProgramData\ ... IT policies etc.

Found GitHub Desktop [GitHub.GitHubDesktop]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://desktop.githubusercontent.com/releases/2.8.2-4423bb9d/GitHubDesktopSetup-x64.exe
  ██████████████████████████████   110 MB /  110 MB
Successfully verified installer hash
Starting package install...
Successfully installed

**Comment by icedream** [comment]
I have found out something interesting: WinGet will let you know the URL from which it downloads the installer, so I decided to check whether the actual installer itself is at fault here, and it seems it is not, but I'm also not quite sure what's going on here.

For one, if you try to run the Discord installer WinGet downloads into `%localappdata%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet`, that EXE will refuse to work even if not executed from WinGet and executed with the same command-line parameters (WinGet runs it with `/s`).

If you download the EXE file through your browser instead **or** you decide to copy the EXE file WinGet downloaded to a new file, then both installer copies will work just fine.

Maybe this will help someone else to debug this? I am currently wandering through the source code and setting up for step-by-step debugging to find out what's going on, up until now I've found nothing useful other than this observation.

**Comment by electronic-dk** [comment]
Looks like after doing repair and reset for the app installer package, discord was able to install from an unelevated prompt. I'll test it with more packages.

**Comment by icedream** [comment]
I wanted to reproduce the issue with step-by-step debugging but I was completely unable to do so. Builds done of the released version `v1.0.11451` in Visual Studio 2019 run 100% fine, however [the build that is in Azure Pipelines](https://dev.azure.com/ms/winget-cli/_build/results?buildId=170552&view=artifacts&pathAsName=false&type=publishedArtifacts) does have the same issue for me.

**Comment by icedream** [comment]
Decided to follow @electronic-dk and run `Get-AppxPackage -Name "Microsoft.DesktopAppInstaller" | Reset-AppxPackage` and now it works for me as well.

**Comment by denelon** [comment]
@icedream we've seen instances where the file path ends up being too long in some cases. I wouldn't be surprised if there were some other installer specific edge cases as well.

**Comment by sreadingMSFT** [comment]
Some info that may help investigate: I also hit the "Unable to write to C:\ProgramData\ - IT Policies may be restricting writing to this folder" issue.
For me the problem was that on that machine the command:
`icacls "C:\Users\<user>\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState" `
showed
`Mandatory Label\Low Mandatory Level:(OI)(CI)(NW)`
This was getting inherited to files in the \TempState\WinGet folder which is where the installers are downloaded to. CDing into the TempState folder and running: 
`icacls c:WinGet /setintegritylevel m`
fixed the issue for me. (Possibly there's a better command to just break the inheritance rather than set to medium explicitly) On other machines I do not see that the TempState folder has this low mandatory label, so I'd speculate that it's either something about different initialization paths for the folder or possibly a version that some machines upgraded through but others skipped.

So yeah, wouldn't be surprised if repair and reset fixes it since those likely recreate the permissions on the appdata as well.

**Comment by JohnMcPMS** [comment]
Looks like @icedream found it was the directory, just as you did @sreadingMSFT .  Most likely the issue has been this ACL the entire time, and we need to ensure that our temp directory does not inherit it.

Good to know that the repair and/or reset is fixing it while we work on an fix in the code to ensure that it doesn't happen.

**Comment by jefer94** [comment]
Doing the same that @icedream i can install postman

**Comment by JiiPee74** [comment]
> I have found out something interesting: WinGet will let you know the URL from which it downloads the installer, so I decided to check whether the actual installer itself is at fault here, and it seems it is not, but I'm also not quite sure what's going on here.
> 
> For one, if you try to run the Discord installer WinGet downloads into `%localappdata%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet`, that installer will refuse to work - as in will try to access `C:\ProgramData\%USERNAME%` - even if not executed from WinGet and executed with or without the same command-line parameters (WinGet runs it with `/s`).
> 
> If you download the EXE file through your browser instead **or** you decide to copy the EXE file WinGet downloaded to a new file, then both installer copies will work just fine. (EDIT: I double-checked with SHA256 hash checks and all hashes matched.)
> 
> Maybe this will help someone else to debug this? I am currently wandering through the source code and setting up for step-by-step debugging to find out what's going on, up until now I've found nothing useful other than this observation.

I noticed that all installers in %localappdata%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet are in some sort of jail because if I try to move any of them to desktop I will get this popup

![image](https://user-images.githubusercontent.com/30867675/122632079-fa8d2700-d0d8-11eb-8823-36a6aecb0807.png)

Maybe this will help to resolve all thouse access denied and IT policies things what some packages are facing.

**Comment by Masamune3210** [comment]
That warning is caused by the files being tagged for a zone that is considered a warning by your Internet settings, could setting the zone be messing with the installers somehow? Maybe they are trying to extract or run something and end up getting redirected for some reason due to the security issue?

**Comment by JiiPee74** [comment]
It's some security issue on TempState folder. I renamed it and created new and problem went away.

**Comment by icedream** [comment]
> 
> 
> That warning is caused by the files being tagged for a zone that is considered a warning by your Internet settings, could setting the zone be messing with the installers somehow? Maybe they are trying to extract or run something and end up getting redirected for some reason due to the security issue?

This is irrelevant to the behavior of the installers and only determines whether Windows will explicitly ask you whether it should allow running the installer or not. The real reason has already been found [with this comment](https://github.com/microsoft/winget-cli/issues/189#issuecomment-856163884).

**Comment by DraconicSalad** [comment]
had to run as adminstrator to resolve my issue
