### ISSUE TITLE
Proxy options support

### ISSUE THREAD

**Issue by KiruyaMomochi** [microsoft/winget-cli#190]
# Description of the new feature/enhancement

Something like:

```powershell
winget install git.git --proxy="http://127.0.0.1:2345"
```

This will make `winget` download `git` through the *proxy server*.

**Comment by jantari** [comment]
Possible proxy configuration options are:

- Environment variables ( e.g. `WINGET_PROXY_URL`)
- Auto-detecting settings from inetcpl.cpl aka IE
- command line arguments
- config file
- registry config separate from IE. This would tie in nicely with ADMX (group policy) templates down the road

**Comment by zuozishi** [comment]
1080端口，老局域网用户了

**Comment by timiil** [comment]
please consider also proxy the download link inside the package , for example , 
```
winget install kodi --proxy http://xxx/
```

please also proxy the download link 'https://mirrors.kodi.tv/releases/windows/win64/kodi-18.7-Leia-x64.exe' which insided the installation package.

**Comment by faustool** [comment]
> Possible proxy configuration options are:
> 
> * Environment variables ( e.g. `WINGET_PROXY_URL`)
> * Auto-detecting settings from inetcpl.cpl aka IE
> * command line arguments
> * config file
> * registry config separate from IE. This would tie in nicely with ADMX (group policy) templates down the road

I would recommend standard variables like HTTP_PROXY or HTTPS_PROXY

**Comment by t-mxcom** [comment]
When adding proxy support, **please do not forget supporting proxies that require NTLM-authentication!!!**
In an enterprise environment where the workstations are joined to a domain, and the users use domain accounts, **entering a password should not be necessary!** (Windows Integrated Authentication)

Thank you!

**Comment by klesh** [comment]
Any plan regarding this feature?

**Comment by sharpninja** [comment]
Really need this!

**Comment by HydrogenDeuterium** [comment]
Need this too!

**Comment by hxse** [comment]
Need it!

**Comment by sourcedelica** [comment]
Surprised this wasn't a 1.0 feature.

**Comment by kybom** [comment]
Need it!

**Comment by qiyuey** [comment]
Need it!

**Comment by fMichaleczek** [comment]
Need it.

1.0 without proxy support ... lol

**Comment by liuilin** [comment]
+1

**Comment by logique233** [comment]
Need it

**Comment by UM-RMeeker** [comment]
Need this as well.

**Comment by Mindzy** [comment]
Also need for `winget upgrade`

**Comment by zhaofeng-shu33** [comment]
Need it

**Comment by d0zingcat** [comment]
Why not try `set http_proxy=http://localhost:7890` and `set https_proxy=http://localhost:7890`?

**Comment by michaelrinderle** [comment]
@d0zingcat because its not socks5.

**Comment by d0zingcat** [comment]
> @d0zingcat because its not socks5.

Maybe you could use Privoxy(windows)/polipo(macOS) to parse socks5 to http?

**Comment by YuanfengZhang** [comment]
Absly need it.

**Comment by gerroon** [comment]
15k stars and no proxy support? I thought this was a joke. This is bloody needed

**Comment by Dragon1573** [comment]
This feature is so important that many users want it! Can't wait for it.

I'm current using a proxy application (CFW) on my own device. I really want `winget.exe` can automatically detect system proxy settings, so I can only change the proxy state of CFW for managing almost every other applications on the device.

**Comment by eternalphane** [comment]
@Dragon1573 Actually `winget` can detect system proxy at current. You just need to disable the Delivery Optimization service by setting `network.downloader` to `wininet`.

**Comment by Dragon1573** [comment]
@eternalphane That's nice! I'm currently using `wininet` as the `network.downloader`. Now I switch my network topology, from using a `localhost` proxy with CFW to using a LAN proxy with CFA (Clash for Android). I launch the CFA on my phone and provide WIFI connection and proxy service for the laptop. I'm using that proxy as a system proxy and everything works fine.

Thank you!

*****

CFW provide `Service Mode` and `TUN Mode` for users, `winget.exe` will rarely encounter a network error with `TUN Mode` enabled. Maybe disable this mode is better ...

**Comment by gaozhe3321** [comment]
Need it!

**Comment by neoribs** [comment]
Need it

**Comment by SignFinder** [comment]
Need it

**Comment by ChesterZengJian** [comment]
Need it

**Comment by lo-w** [comment]
need it
BR//lo

**Comment by cgfork** [comment]
+1

**Comment by biaocy** [comment]
Need it.

**Comment by toshiya14** [comment]
Need it.

**Comment by gerroon** [comment]
> 

The whole point of asking for a custom proxy support is to make sure one is not using systemwide proxy. The systemwide proxy opens connections to everything else o the system.

**Comment by walkonbothsides** [comment]
Need it!

**Comment by NJCCJohnWatson** [comment]
We need it !  not that messive .env etc

**Comment by altiris4ever** [comment]
As a workaround i use: "bitsadmin /util /setieproxy localsystem MANUAL_PROXY "
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-util-and-setieproxy

**Comment by denelon** [comment]
All,

Please be respectful of others who are watching this Issue. Every comment is sent out as an e-mail to every user watching this Issue. Adding comments like "Need it" or "+1" is just causing more noise. We track relative priority by the number of 👍 on the original post for the Issue. I've hid the majority of these comments, as they do not add to the scope of the issue or offer support for others who also want this feature and are essentially "subscribed" because they have added their 👍.

This issue is now high on the backlog. We have several security concerns we have to address in order to enable this feature. As soon as we have a design that is acceptable for our security requirements, we will look to sequence this work for engineering.

You can see how we prioritize work on the [Roadmap](https://github.com/microsoft/winget-cli/discussions/2063).

**Comment by itodouble** [comment]
Is there any plan that can be used ?

**Comment by char-46** [comment]
It's been more than three years since this issue was created, and we see that this issue has a linked PR #1776, which solves some problems. After that PR, this issue was added to the milestones: v1.3-Client, v1.4-Client, v1.5-Client and now v.Next-Client. As the differences between commits increase due to the development of master branches, merge PR has become a challenge by now. Moreover, according to RoadMap, this issue is already the issue with the largest number of 👍 among milestone: v.Next-Client. Can we first merge this PR as an experimental feature, and then gradually fix it according to the new problems we encounter?

**Comment by denelon** [comment]
We have to adhere to our internal security standards which is why that PR hasn't been merged. We're working on getting the documentation together for our security review, and then we'll be able to either start from that PR or create a new one with the approved method. It will initially start out as an experimental feature in a preview and then it can be made stable feature in the next stable release. 

I've changed how we're tracking work across milestones to avoid the constant movement. We've had several other high-priority features and bug fixes in progress, but this has made it to the top of the list for asks from the community.

**Comment by denelon** [comment]
Hey everyone, I know it's been a long time coming, but we have had our initial security review. We will be submitting a specification document and will work on final review and then we can get into implementation.

* We will need GPO (Group Policy Objects) for enterprise control of WinGet with respect to proxy support.
* Specifying a default proxy for WinGet will require administrative permissions.
* The CLI will not require administrative permissions to pass "--proxy <an HTTPS proxy>" (will not override GPO).

I want to thank @eternalphane for the draft PR:
* https://github.com/microsoft/winget-cli/pull/1776

**Comment by tlsalex** [comment]
waiting for the good news

**Comment by cuellartech** [comment]
> Hey everyone, I know it's been a long time coming, but we have had our initial security review. We will be submitting a specification document and will work on final review and then we can get into implementation.
> 
> * We will need GPO (Group Policy Objects) for enterprise control of WinGet with respect to proxy support.
> * Specifying a default proxy for WinGet will require administrative permissions.
> * The CLI will not require administrative permissions to pass "--proxy " (will not override GPO).
> 
> I want to thank @eternalphane for the draft PR:
> 
> * [Add basic proxy support #1776](https://github.com/microsoft/winget-cli/pull/1776)

You mention a GPO. Is there a plan to also include Intune, using a configuration policy, as a means for enterprise control? 

We have many workstations that are not domain joined, only Entra joined, that have no GPOs and no intention of introducing any.

**Comment by mominshaikhdevs** [comment]
the Intune situation should be considered too as a part of supporting proxies. this issue can be closed then.

**Comment by denelon** [comment]
Hey everybody, the "Proxy" experimental feature is available in the latest WinGet 1.8 preview release.

I'd like to see a few folks test the feature out, but I don't want to add more noise here on the issue that triggers e-mails to everyone subscribed.

Please test out the feature and provide your results over at:
* https://github.com/microsoft/winget-cli/discussions/4428

**Comment by denelon** [comment]
We're getting ready to make the proxy support a stable feature for WinGet 1.8.

When that release is created, I'll be closing this issue.

If there are any additional requests related to proxy support, please create new issues.

**Comment by aith85** [comment]
What about proxy with user/pass authentication ?

**Comment by grappas** [comment]
And what about socks proxy?
