### ISSUE TITLE
Apparently, [Microsoft.EdgeWebView2Runtime] has encountered another problem

### ISSUE THREAD

**Issue by Vzz1c** [microsoft/winget-cli#1904]
### Brief description of your issue

Even if the version of Microsoft EdgeWebView2Runtime is the latest, the current version will be repeatedly downloaded and installed when upgrading or importing.

**Comment by jedieaston** [comment]
Can you run `winget list Microsoft.EdgeWebView2Runtime` and post the output? I want to check something real quick.

**Comment by Vzz1c** [comment]
> 您可以运行`winget list Microsoft.EdgeWebView2Runtime`并发布输出吗？我想快速检查一些东西。

I found the reason, because my computer actually exists at the same time two EdgeWebView2Runtime version, a latest version and the old version, I uninstalled and reinstalled, now is no longer a problem, but, why there are two versions at the same time? The old version is not updated correctly?

**Comment by Karl-WE** [comment]
the error code for Webview happens because winget upgrade finds the package and reports there is a new version but effectively it is the same version if you dl the file from the repo and try to install it manually. Have reported this, not as detailed in #752 and attached logs for this issue. Hope this helps.

**Comment by Karl-WE** [comment]
Thanks for the follow up!

**Comment by denelon** [comment]
We've made several improvements to WinGet in the install and upgrade flows. Is this problem still happening?
