### ISSUE TITLE
Why, For the Love of God, why do you allow duplicate package names? Please force uniqueness - Thank You!

### ISSUE THREAD

**Issue by JustAnotherG** [microsoft/winget-cli#1905]
So, I just discovered the new Windows package manager is on my Windows 11 system so I thought I would try it to update from PowerShell Major version 5 to PowerShell Major version 7.

So, I typed winget install PowerShell and it responds with 2 packages with the ..."exact same name". Why would you allow this? Yes, they have different attributes as far as their IDs and even the sources. But this just confuses people. Also, what is maximum length of a package name? It looks ridiculously small, like you wanted to mimic Linux exactly? It looks the programmers who wrote this have pixelphobia. What is the deal? Use the screen, please! Let's go with a max of at least 32 characters please.

Looks like it's off to a good start but allowing duplicate package names is just silly.
![winget](https://user-images.githubusercontent.com/25889253/152664066-a3477d42-49d2-41b5-8e58-cd74acbddd16.png)

And lastly, as a new user of this package manager, what do I do now?? Well, I'm sure I'll figure it out soon enough but this is not a user friendly experience and I thought that was the whole purpose of package manager. The package manager is talking about ambiguity and I have no idea how to resolve it until I dig deeper into the arcane magic of the programmers heads.

**Comment by Masamune3210** [comment]
Wrong repo, go report to winget-pkg

**Comment by JustAnotherG** [comment]
Can a moderator please move my message to the appropriate discussion?

**Comment by jedieaston** [comment]
It’s because the same package is available from multiple sources. There are several issues here and at the other repo that discuss how to fix this problem, but if you want to get rid of it now, the `-s` flag will allow you to select a specific source. 

Alternatively, `winget source remove msstore` will allow you to only search the community repo.

**Comment by jpawlowski** [comment]
To make this more complex, there are fairly significant differences between some packages from different sources.
PowerShell Core is actually a very good example but generally speaking, the msstore apps are more limited in what they can do on the system (due to containerization, kind of). See [Installing PowerShell on Windows - Known limitations](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2#known-limitations) for more details.
On the other hand, the winget Package variant uses the MSI installer variant and comes with the full features while a more convenient update process is also possible (thanks to winget), something that would be more painful when manually installing software as it is up to the software itself to know when it needs an update.

That being said, it is actually "okay" to see more than one package to install the same software, knowing that each package may (or may not) be slightly different. That's very specific to the software you intent to install and obviously to the package maintainer(s).

I personally think it is good to have the same name property for more than one package as long as it is unique within the specific source. This will allow you to figure out that those packages are actually providing the same peace of software, just in different variants.

I can understand the agony of choice. Unfortunately this is something that you need to deal with and always needed to. It just becomes more apparent to you know that you can see it more easily side by side. This can also be seen as a benefit, although it might not be very obvious to the typical user just wanting to install software as before.

In my opinion, Winget is actually trying to help and clean up "the mess" of having multiple distribution channels side by side. This is also unique in comparison to the other package managers the community provides for Windows (e.g. Scoop, Chocolatey). The potential here is huge, but as we can see, is also making this more complex to architect and implement.

**Comment by JustAnotherRequest** [comment]
@jedieaston 

Just Add A Feature Request for setting  Default Installation/Upgradation Source to avoid this. 

for example :  

```cs
> winget install/Upgrade Crap

Found multiple packages named Crap. Default Source is <YourSource>, 
Installing/Upgrading from <YourSource>
...
```

**Comment by jedieaston** [comment]
It's been requested in https://github.com/microsoft/winget-cli/issues/1488.

**Comment by denelon** [comment]
Uniqueness is enforced at a source level. 

As this issue has been discussed and there are other features to help resolve the problem in the future, I'm going to go ahead and close this issue.
