### ISSUE TITLE
[FEATURE] Add support installation on Windows Server 2022

### ISSUE THREAD

**Issue by David-Noble-at-work** [microsoft/winget-cli#1929]
### Brief description of your issue

Please start by providing a well-advertised and discoverable download and a list of prerequisites with download links. This should be straightforward. I think you will find that most people will say the winget cli is most useful on systems without Microsoft Store availability. It is surprising that a package manager isn't standard on server class machines.

### Steps to reproduce

1. Search the internet for "winget-cli downloads", "winget-cli releases", and "install winget-cli on Windows Server".

2. Find this site and other Microsoft sites that say things like:I

   - Installation on Windows Server isn't supported, 
   - You might be able to install on Windows Server 2022
   - You'll need to instal prerequisites on Windows Server 2022

3. Observe there are third-party articles with instructions and bad links (stuff it seems someone has removed).

4. Observe that this site either hides or obscures anything that would make it possible for someone to discover what's required to install on Windows Server 2022.

5. Suspect that the developers on this site don't care about Windows Server consumers and be sad about using Microsoft Windows at all.

### Expected behavior

Find release notes, download links, and instructions for installing winget-cli on the platform where it is perhaps most useful: Windows Server.

### Actual behavior

- Find release notes, no download links, no instructions, and unanswered questions on support Channels.
- Find instructions from third parties with download links that someone has removed.

### Environment

```shell
Windows Server 2022 machine on Azure that costs quite a bit of money and doesn't include a package manager.
```

**Comment by jedieaston** [comment]
I'm guessing you've already seen #754, but the long story short is that even if installation of winget is supported for Server 2022, it is just about unusable[^1] due to the issues described in #1474. Those are actually upstream OS issues, which may have a workaround specifically for winget at some point but they are mostly waiting to see if it gets resolved in Windows.

There would be very little utility in a package manager where you have to be sitting on the console in order to use it. Once that issue is resolved the other ones should be easy to fix. 

If you're feeling brave, I've been [compiling standalone builds](https://github.com/jedieaston/winget-build) of winget from the master branch that should "just work" on Server 2022. It might be worth me freezing a version that matches the stable release, although it would still be extremely unsupported by Microsoft. They will work just fine over SSH/PSRemoting, and no permissions changes are necessary. 

[^1]: Yes, you can force change the permissions on stuff in WindowsApps to make it work. But that's an arcane workaround that will possibly break stuff with appx.
