### ISSUE TITLE
Support for enterprise application install/update

### ISSUE THREAD

**Issue by CookeDanny** [microsoft/winget-cli#193]
Would love to see integration with Intune/MEM to globally push and update supported applications

**Comment by bbarry** [comment]
And/or the ability to maintain a package list of installables at an org level. 

Ex: vscode is an approved package, go ahead and install it...

once installed, Intune/MEM/GFI/... keeps the installed packages up to date (vs code might be a bad example because it self updates but still if you never open it, it never updates).

**Comment by vedantmgoyal2009** [comment]
@trenly Duplicate of https://github.com/microsoft/winget-cli/issues/215

**Comment by vedantmgoyal2009** [comment]
cc @denelon

**Comment by denelon** [comment]
Duplicate of #215
