### ISSUE TITLE
Add option to specify winget install directory

### ISSUE THREAD

**Issue by jwlodek** [microsoft/winget-cli#201]
# Description of the new feature/enhancement

I usually install certain programs onto a secondary `D:` drive, so it would be nice if I could specify a different location than default. This is mainly for when I have a smaller SSD and larger hard disk side by side

# Proposed technical implementation details (optional)

Some form of system-wide configuration to set default install location.
Certain programs I would like to install in the default location however (things that I want to run off of the SSD), so there should be a flag that can override default configured install location. Ideally any specified location should be added to the PATH so that I know I have access to whatever I install.

**Comment by arjvintech** [comment]
I agree -- the specification of the install drive would be very helpful.  It would be nice if the drive could be specified:

1. On all winget installs via a settings file
2. With the ability to override on a per winget install call

I believe it would be better to separate the PATH issue from this feature request. I can think of several instances where updating the PATH may not be desired.

**Comment by JohnMcPMS** [comment]
For individual invocations, you can use:
 -l,--location     Location to install to (if supported)

Not all installers support passing an install location on the command line, so this won't guarantee things though.

**Comment by G0rocks** [comment]
These issues are similar: #337 , #489

**Comment by dpurge** [comment]
Can we push manifest authors more to support "--location" parameter?

Eg. require that packages which do not support "--location" *must* declare lack of support, so that winget knows whether any given package supports it.

If "--location" was specified, but package does not support it, winget could return an error, or optionally ask "This package does not support --location parameter, do you want to continue installation in the default location? (y/N)"

I do not like winget silently ignoring my "--location" parameter and installing in the default location.
(Looking at you, wingetcreator)

**Comment by yorehiwo** [comment]
That would be awesoem if you could do that! I only have a 128 GB M.2 SSD where Windows is installed. So because of that I have to install all my Programms to "D:/Program Files" or "D:/Program Files (x86)".

**Comment by yorehiwo** [comment]
That would be awesome if you could do that! I only have a 128 GB M.2 SSD where Windows is installed. So because of that I have to install all my programms on my secondary SATA SSD drive to "D:/Program Files" or "D:/Program Files (x86)" which has 2 TB capacity. Physically separating my programms from my OS also means less pain if I have to reinstall Windows.

**Comment by yorehiwo** [comment]
That would be awesome if you could do that! I only have a 128 GB M2 SSD where Windows is installed. So because of that I have to install all my programms on my secondary SATA SSD drive to "D:/Program Files" or "D:/Program Files (x86)" which has 2 TB capacity. Physically separating my programms from my OS also means less pain if I have to reinstall Windows.

**Comment by yorehiwo** [comment]
That would be awesome if you could do that! I only have a 128 GB M2 SSD where Windows is installed. So because of that I have to install all my programms on my secondary SATA SSD drive to "D:/Program Files" or "D:/Program Files (x86)" which has 2 TB capacity. Physically separating my programms from my OS also means less pain if I have to reinstall Windows.

**Comment by Copystrike** [comment]
Should this issue not be closed since you can now achieve it with https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#default-install-root ?

**Comment by denelon** [comment]
Thanks for calling this out.

**Comment by qwell** [comment]
I'm pretty confused by the closure of this issue.

1. The docs show that the `defaultInstallRoot` setting requires the package manifest to have `InstallLocationRequired`.  As of today, a [search in winget-pkgs](https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs%20path%3A%2F%5Emanifests%5C%2F%2F%20InstallLocationRequired&type=code) shows that there are a total of two packages that have ever set `InstallLocationRequired`.  `AutoHotkey.AutoHotkey` added the setting in 2.0.2 and then removed the setting in 2.0.3, and `nepnep.neofetch-win` has it set to false; in other words, there are zero packages that use this.
2. There is a separate setting for this in Windows (`Storage Settings` > `Where new content is saved` > `New apps will save to`) that also doesn't appear to be used.

As it stands now, there does not appear to be any way of specifying a default install location for any non-portable packages (where a different setting is used).  Setting `--location` when installing new packages is rather burdensome and becomes even more of a problem when taking #2207 into account; `--location` also requires a full path, meaning that you can't just create an alias that always sets it to something like `D:\Program Files\`.

Am I completely missing something?

**Comment by SheepCommander** [comment]
> This setting is only used when a package manifest includes `InstallLocationRequired`

One year later, only SEVEN packages have `InstallLocationRequired` set to true. So there's still not a way to specifcy a install directory?
