### ISSUE TITLE
Winget shows an installed package but can't update it

### ISSUE THREAD

**Issue by gbritton1** [microsoft/winget-cli#2070]
### Brief description of your issue

winget show works, winget update doesn't
```

PS C:\Users\geral> winget show --id 9PJPW5LDXLZ5
Found Python 3.10 [9PJPW5LDXLZ5]
Version: Unknown
Publisher: Python Software Foundation
Publisher Url: https://www.python.org/
Publisher Support Url: https://www.python.org/doc/
Description: Python is an easy to learn, powerful programming language. It has efficient high-level data structures and a simple but effective approach to object-oriented programming. Python’s elegant syntax and dynamic typing, together with its interpreted nature, make it an ideal language for scripting and rapid application development in many areas on most platforms.

==========
Expected your existing copy of Python to run? Either update your PATH to raise its priority, or open "Manage App Execution Aliases" from Start to disable the shortcuts.
==========

The Python interpreter and the extensive standard library are freely available in source or binary form for all major platforms from the Python Web site, https://www.python.org/, and may be freely distributed. The same site also contains distributions of and pointers to many free third party Python modules, programs and tools, and additional documentation.

The Python interpreter is easily extended with new functions and data types implemented in C or C++ (or other languages callable from C). Python is also suitable as an extension language for customizable applications.
License: https://docs.python.org/3.10/license.html
Privacy Url: https://www.python.org/privacy/
Copyright: (c) Python Software Foundation
Agreements:
Category: Developer tools
Pricing: Free
Free Trial: No
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
Seizure Warning: https://aka.ms/microsoft-store-seizure-warning
Store License Terms: https://aka.ms/microsoft-store-license

Installer:
  Type: msstore
  Store Product Id: 9PJPW5LDXLZ5
PS C:\Users\geral> winget upgrade --id 9PJPW5LDXLZ5
No installed package found matching input criteria.
PS C:\Users\geral> winget upgrade --name 'Python 3.10'
No installed package found matching input criteria.


```

### Steps to reproduce

1. run winget show for Python package:  winget show --id 9PJPW5LDXLZ5
2. run winget upgrade for same package: winget upgrade --id 9PJPW5LDXLZ5

### Expected behavior

expected winget to upgrade Python to latest level

### Actual behavior

Receiving message "No installed package found matching input criteria."

### Environment

```shell
winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
PS C:\Users\geral>
```

**Comment by ItzLevvie** [comment]
WinGet currently doesn't support updating Microsoft Store apps. You will have to do that through Microsoft Store.

A workaround is to use `winget install` instead.

**Comment by ItzLevvie** [comment]
> I did not install Python via the MS Store but rather from the Python download page.

cc @gbritton1: `9PJPW5LDXLZ5` is a Microsoft Store ID and I'm not sure where that came from if you didn't use the `msstore` source in WinGet.

https://www.python.org/downloads/release/python-3104/ doesn't show any MSIX releases for Windows. It only has downloads for the EXE releases.

> It does not show on my list of installed apps in MS Store.

Would you be able to post your entire `winget list` so it's possible to trace the issue down?

This is what I see on my VM (EXE is `Python.Python.3`):
![image](https://user-images.githubusercontent.com/11600822/161791704-f8f474ff-ee35-4f44-b79a-7397b7fb0b58.png)

This is what I see on my VM (MSIX is `PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0`):
![image](https://user-images.githubusercontent.com/11600822/161793007-46e692d6-4539-4791-99ea-6bf6c13892df.png)

I'm 100% sure that you downloaded it using the `msstore` source which means your updates are delivered via Microsoft Store instead of WinGet.

> In any case, perhaps winget could report "not installed via winget" instead of the current "No installed package found" which seems to be confusing when winget show does, indeed, find the package.

At the moment `winget list` will show all applications on your PC even if you installed it outside of WinGet.
