### ISSUE TITLE
Inno installer mode does not use /suppressmsgboxes

### ISSUE THREAD

**Issue by chbwien** [microsoft/winget-cli#2093]
### Brief description of your issue

When I set the installer mode to inno, obviously only the silent parameter /silent is used. The parameter /suppressmsgboxes is NOT used. So Inno-Installers will stop with messageboxes. See https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

### Steps to reproduce

Use any Inno installer with suppressible message boxes, create a package and try to install it.

### Expected behavior

the silent parameters should be: /silent /suppressmsgboxes
the very silent parameters should be: /verysilent /suppressmsgboxes

### Actual behavior

/suppressmsgboxes is not used -> hence problems in silent mode with messageboxes.

### Environment

```shell
Windows-Paket-Manager (Vorschau) v1.3.431-preview
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.19044.1645
Paket: Microsoft.DesktopAppInstaller v1.18.431.0

Protokolle: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by OfficialEsco** [comment]
IMO /suppressmsgboxes should not be default because it may contain important information, so my question is, what message box are you having issues with?
I do however agree with using /suppressmsgboxes for certain pacakges which do have useless popups.

In the case of TUitTUWien.TUtoolbox which you updated i see no popup on clean installation

However i see this when installing a lower version (2022.0.0.437)
![VirtualBoxVM_y4MFS6IFLP](https://user-images.githubusercontent.com/15158490/163422533-aac45a50-1598-4623-b7cd-7c114d12ada2.png)
When pressing No i get
![VirtualBoxVM_q7Mc2Stdfd](https://user-images.githubusercontent.com/15158490/163422724-2e38e564-1a5d-49bd-9bf4-7014bada80a4.png)
When i use /suppressmsgboxes it just terminates with exit code 1 which would then make the user post a issue on our repo without the proper information which the message boxes was telling the user about.

**Comment by chbwien** [comment]
This is a very special case. But the problem is: any kind of silent should go through without user interaction. Therefore inno knows the suppressmsgbox feature. In the installer code, you can use special messageboxes, that have a default, when suppressed.
So if you create an inno installer, that is supposed to run in silent or verysilent mode, you must use no messageboxes at all or supressable ones, or you will get stuck (especially when using verysilent, because there is no userinterface shown). There is ofcourse a discussion, why silent or verysilent does not use the suppressmessagebox itself, but there is not an easy answer. Fact is: without suppressmsgboxes you are stuck in verysilent mode and get in trouble with silent mode.

**Comment by OfficialEsco** [comment]
Packages does not pass validation if its not 100% silent.
Therefore the popups are created to be informational to the user, one case i can think of would be a prompt to kill the process in case the user got unsaved work.

If you are experiencing issues with a package its most likely caused by a Upgrade, IMO you should explain the issue so its publicly visible in the PR/Issue so there is a reference point and then use the Custom or Upgrade field depending on where the popup occurs.

**Comment by denelon** [comment]
I agree with @OfficialEsco here.

We designed WinGet so it could be used in scipts where there isn't a person to review UI prompts or click buttons.

Worst case scenario users can use "--override".

Until we get:
* https://github.com/microsoft/winget-cli/issues/2972

I think we need to have "silent" truly mean no user interaction, and ideally no "pop-ups".

**Comment by chbwien** [comment]
Exactly. Therefore the standard inno mode should include /supressmsgboxes...
