### ISSUE TITLE
Move `ReleaseDate` field to locale manifest

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-cli#2108]
### Description of the new feature / enhancement

I know there are several packages which already have `ReleaseDate` in their installer manifest, so we may hold up until:

* https://github.com/microsoft/winget-pkgs/issues/55921
* https://github.com/microsoft/winget-pkgs/issues/125

are implemented.

`ReleaseDate` field should be in Locale manifest instead of Installer manifest. Here's why:

- It's more related to "Package-Metadata" rather than the installer's (meta)data or properties.
- `ReleaseDate` is for a specific version of a package and not for the installer.

### Proposed technical implementation details

Make changes in the client🤔, schema, winget-create, and pipelines.

**Comment by Trenly** [comment]
> ReleaseDate is for a specific version of a package and not for the installer.

I disagree. I've seen a few times where the release date for an exe installer is not the same as the release date for an msi installer, even if they are the same package version. 

> It's more related to "Package-Metadata" rather than the installer's (meta)data or properties.

Again, I disagree, especially since we don't know how Channels will be implemented yet. A beta installer will most likely have a different release date than a stable installer. If "channel" is defined at the installer level, then release date also must be defined at the installer level.

> Make changes in the client🤔, schema, winget-create, and pipelines.

This would be a breaking change anyways, and would have to wait until schema 2.0

**Comment by denelon** [comment]
I think in this case, I agree with @Trenly. The release date is per installer. I've seen cases where different architectures have different release dates for the same "version" of a package.
