### ISSUE TITLE
Winget can't find installed package to uninstall

### ISSUE THREAD

**Issue by cbc02009** [microsoft/winget-cli#2118]
### Brief description of your issue

I installed FreeCAD via winget and now I'm unable to uninstall it.

![image](https://user-images.githubusercontent.com/39525900/164977976-85188bcd-75c9-49af-b91e-05dcdfc701c2.png)

### Steps to reproduce

Install FreeCAD with `winget install FreeCAD.FreeCAD`
Attempt to uninstall with `winget uninstall FreeCAD.FreeCAD`

### Expected behavior

program should be found an uninstalled.

### Actual behavior

Winget cannot find installed package

### Environment

```shell
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.613
Package: Microsoft.DesktopAppInstaller v1.17.10271.0
```

**Comment by ItzLevvie** [comment]
1) Install 0.19.3
2) Upgrade to 0.19.4
3) Uninstall doesn't work because it installed FreeCAD side-by-side:
![image](https://user-images.githubusercontent.com/11600822/165584087-0062fdd7-3010-4797-b23a-652a1d5539ee.png)

This will be fixed by a winget-pkgs PR: https://github.com/microsoft/winget-pkgs/pull/58902

cc @cbc02009: You will need to make sure to uninstall the old version of FreeCAD from your PC so that upgrades will continue to work or otherwise WinGet will get confused and won't know which version of FreeCAD to upgrade.

**Comment by JohnMcPMS** [comment]
I tried it out and repro the same experience.  1 version uninstalls fine, but with two it gets muddled.  I created #2129 for this, although I feel like I've done so in the past but couldn't find it.

**Comment by denelon** [comment]
We've been working on the side-by-side scenarios. You could try the latest release and enable the experimental feature on:
* https://github.com/microsoft/winget-cli/releases/tag/v1.8.924-preview

Please provide feedback at:
* https://github.com/microsoft/winget-cli/discussions/4281

**Comment by denelon** [comment]
Is this still a problem with WinGet 1.8?
