### ISSUE TITLE
Error message for 'winget upgrade --all --force --silent'

### ISSUE THREAD

**Issue by thgossler** [microsoft/winget-cli#2198]
### Brief description of your issue

I'm on the preview channel and I get the following error message for over 2 months now.

```
winget upgrade --all --force --silent

Windows Package Manager (Preview) v1.3.692-preview
Copyright (c) Microsoft Corporation. All rights reserved.

The arguments provided can only be used with a query.
```

### Steps to reproduce

Nothing special, get the latest preview version and execute this command line.

### Expected behavior

As before this command and arguments should not yield an error message but install all updates silently.

### Actual behavior

```
winget upgrade --all --force --silent

Windows Package Manager (Preview) v1.3.692-preview
Copyright (c) Microsoft Corporation. All rights reserved.

The arguments provided can only be used with a query.
```

### Environment

```shell
Windows Package Manager (Preview) v1.3.692-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.708
Package: Microsoft.DesktopAppInstaller v1.18.692.0

Executed in PowerShell 7.2.3 and 7.2.4 and cmd.exe (Windows 11 latest release, not Insider)
```

**Comment by thgossler** [comment]
I have to install the previous stable version every time again
WinGet-stable__Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
to get this working. Store is always auto-updating to the broken version on the next day.

**Comment by jedieaston** [comment]
This is intentional behavior, at least it was when I wrote that check. I believed that you shouldn't be able to do a hash override for all of the packages in a `winget upgrade --all` since you may have not looked at the list of packages prior, meaning you may get a compromised download. If you want to `--force`, you'll have to give the name of the package you want to upgrade.

`winget upgrade --all --silent` will work. Is there a specific package you are commonly hitting hash errors with? If so, we can see about making sure that it gets updated faster in microsoft/winget-pkgs.

**Comment by thgossler** [comment]
Thanks for the explanation, makes sense. I was not aware that it comes from the --force flag which I can live without.
