### ISSUE TITLE
Firefox version misreporting

### ISSUE THREAD

**Issue by Aevrin** [microsoft/winget-cli#2380]
### Brief description of your issue

When running winget today it reported the version installed as 94 instead of 103.0

### Steps to reproduce

ran winget.exe upgrade, viewed the output
Firefox is version 103.0, but reports as 94.  I validated both Firefox directly and patchmypc.exe

### Expected behavior

It should report one unknown version for Battle of Wesnoth: 

winget.exe upgrade
Name               Id                       Version Available Source
--------------------------------------------------------------------
Battle for Wesnoth Wesnoth.BattleForWesnoth Unknown 1.17.4    winget
1 upgrade available.

### Actual behavior

winget.exe upgrade
Name               Id                       Version Available Source
--------------------------------------------------------------------
Mozilla Firefox    Mozilla.Firefox          94.0.2  103.0     winget
Battle for Wesnoth Wesnoth.BattleForWesnoth Unknown 1.17.4    winget
2 upgrades available.

### Environment

```shell
winget.exe --info
Windows Package Manager v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.832
Package: Microsoft.DesktopAppInstaller v1.17.11601.0
```

**Comment by Trenly** [comment]
I believe this is due to when @jedieaston added the Firefox 103.0 package to the repository, he included the Mozilla Maintenance Service AppsAndFeaturesEntry, which is a non-primary ARP entry. 

When firefox upgrades itself, not using the firefox installer, the Mozilla Maintenance Service isn’t upgraded at all. Because Firefox generally auto-updates, having the non-primary ARP entry specified likely caused it to detect a mismatch if the Maintenance Service is outdated.

![C5D0538A-E688-4193-93E5-91E68CA8F201](https://user-images.githubusercontent.com/12611259/181277322-9bf3a9e9-0170-425c-b51f-abe513dcddf7.jpeg)

I’m hoping https://github.com/microsoft/winget-pkgs/pull/67706 will resolve this issue

**Comment by jedieaston** [comment]
I thought non-primary didn't matter if the version numbers were the same. I'll note this for the future, but does anyone know *why* it matters? Is Mozilla's updater in the browser not updating the maintenance service?

**Comment by Trenly** [comment]
> Is Mozilla's updater in the browser not updating the maintenance service?

100% Correct!
