### ISSUE TITLE
Use manifest version if installer does not provide it

### ISSUE THREAD

**Issue by giggio** [microsoft/winget-cli#2496]
### Description of the new feature / enhancement

Currently if a installer does not contain the version then the version is shown as `unknown` by Winget, and Windows does not show any version information.
This makes the user use `--include-unknown` to upgrade the package, which is also inconvenient.
My suggestion is that if the package was installed via winget, then it should store somewhere that version, and use it if the installer does not provide it. If it does, than it should supersede the version from the manifest.

### Proposed technical implementation details

N/A

### Additional context
See bugs for:
https://github.com/coreybutler/nvm-windows/issues/851
https://github.com/microsoft/winget-pkgs/issues/37597

**Comment by giggio** [comment]
@trenly I'm not sure this is a duplicate. The proposed solution is different, but I guess it would solve the problem. Maybe that issue need more information, I could not find it when searching.

**Comment by Trenly** [comment]
At its core, it is the same. Winget uses the registry Display Version to track which packages are installed. In order to accomplish your proposal of tracking which version has been installed, the version needs to be added into the Registry. In order to know when it would need to be added to the registry, there would have to be information in the manifest that the registry entry must be updated - either through a `null` DisplayVersion in the AppsAndFeaturesEntry key in the manifest, or by having a dedicated key indicating the override is necessary. 

I think it's the case here that the linked issue may need more information, or more feedback on how it could be used / problems it would solve.

**Comment by giggio** [comment]
Ok, thanks for the explanation, I'll try to add a comment there to try to make it easier to find.
