### ISSUE TITLE
"The ms-appinstaller protocol is disabled by policy"

### ISSUE THREAD

**Issue by CG5isthebest** [microsoft/winget-cli#2580]
### Brief description of your issue

I cannot use the package manager on the latest version of Windows 10 when using the ms-appinstaller protocol.

### Steps to reproduce

Use this in a tab ms-appinstaller:?source=https://aka.ms/getwinget, have the policies not installed, and it will happen

### Expected behavior

For it to install

### Actual behavior

Cant install

### Environment

```shell
none
```

**Comment by CG5isthebest** [comment]
Nevermind lol

**Comment by ItzLevvie** [comment]
It was disabled due to https://github.com/microsoft/winget-cli/issues/725#issuecomment-1001017823.

Read more in https://techcommunity.microsoft.com/t5/windows-it-pro-blog/disabling-the-msix-ms-appinstaller-protocol-handler/ba-p/3119479

"Update: August 5, 2022 – The fix to enable the ms-appinstaller protocol handler was rolled out to Windows 11 Insider Preview Build 25147 for the Dev Channel. We will provide updates on the availability of the fix when we have them."
