### ISSUE TITLE
"winget upgrade --all --include-unknown" is not upgrading properly

### ISSUE THREAD

**Issue by cmdshft** [microsoft/winget-cli#2631]
![Screenshot 2022-10-23 112513](https://user-images.githubusercontent.com/8571823/197409272-36858bf4-fb4d-4507-8e2e-f162782b2bc0.png)

When I run the above command, I still have packages that show as available for download, but it will just reinstall a few packages here and there, and not clear out the package in the list. I can run this over and over and nothing changes.

**Comment by denelon** [comment]
The "--include-unknown" flag was added for users who wanted to try and upgrade any software that does not report a version in the registry for Windows Apps & Features. The reason they are "ignored" by `winget upgrade` is because there is no way to know if the manifest is a newer version than what is currently installed.

Prior to adding the "--include-unknown" feature and removing software that didn't report its version from `winget upgrade`, users would be in what appeared to be an upgrade loop as you are describing. 

By adding "--include-unknown" to every subsequent call of `winget upgrade --all`, winget is attempting to apply upgrades to software that may already be up to date. The publisher of those packages is not providing a version in the registry that can be used to determine if the software is current.

**Comment by Viquitus** [comment]
sometimes when i update its shows this on the final (when everything updated) 1 Packages are fixed and need to be updated explicitly. (translated from brazillian)

**Comment by SoloisticRamonymous** [comment]
winget update --all --include-unknown

Or Paket Error


ttps://cdn.winget.microsoft.com/cache/source.msix

https://learn.microsoft.com/de-de/windows/msix/app-installer/install-update-app-installer?fbclid=IwZXh0bgNhZW0CMTAAAR5B1dhlGwO92FY_hiDz0LZffyeJH9ZqEp1aGk4tVyxp1GDvrPRzHHKwuPJKYg_aem_sVnUNNm4XWsGX7eqaJVvGw
