### ISSUE TITLE
Opt-Out of Telemetry

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#279]
# Description of the new feature/enhancement

I'd like to be able to opt-out of telemetry for the Windows Package Manager client.

# Proposed technical implementation details (optional)

A command to control (disable / enable) telemetry in the client.
The --info output would display the state of the telemetry setting.

If the OS settings are disabled, the client would not report telemetry regardless of the setting.
The setting would persist if the client was updated/upgraded

**Comment by doctordns** [comment]
I would prefer to see telemetry be opt-in.

**Comment by bdcarr** [comment]
To play megacorp's advocate, telemetry is very useful for making design decisions backed by data. Sometimes people will say "we want this", then you make a change based on that and it has unintended consequences which could've been avoided with analytics that tell you how people _actually_ use the software.

Given your average joe's propensity to plow through installs with the default settings, it's best to make things opt-out rather than opt-in, otherwise your data is nearly useless. There should absolutely be an opt-out though - laws aside, it's a total dog move to force data collection on users.

`homebrew` handles this well, giving you a notice about telemetry when you first install it and offering two methods for opting out: an environment variable `HOMEBREW_NO_ANALYTICS` and a command `brew analytics off`.

So yeah, thanks @denelon, you seem to be going about this the right way now.

**Comment by ShadowJonathan** [comment]
I agree with @bdcarr, there's a reason why Microsoft pushes for telemetry everywhere, but at least the minimal service they can do to the community is **tell which data they're forwarding** and **give the option to opt-out**, as I personally think those are reasonable requests in 2020.

Even if it's a dry statement or gigantic table about which specific grains of data are pushed to analytics servers, it's more than a wildcard vague "everything", or no information at all.

Adding the option to scale down more specific data to generics and basics in a checkbox list would be nice too (if the list is too large and asks too much), but those two previously-mentioned requests are more important than this cherry-on-top.

**Comment by zooba** [comment]
Here's the "dry statement" about what telemetry is collected: https://github.com/microsoft/winget-cli/blob/master/src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h

You might have to search around the sources for calls into these, but I think you can make reasonable guesses from the parameter names. It's also worth noting that this functionality only writes into your local event logs, which means actual collection will only happen when your OS-level settings allow it. Nothing is being uploaded directly from WinGet (unless I didn't spot that part - I'm not actually on the team, so not that familiar with the codebase).
