### ISSUE TITLE
Microsoft.WindowsSDK installer failed

### ISSUE THREAD

**Issue by andylizf** [microsoft/winget-cli#2924]
### Brief description of your issue

Microsoft.WindowsSDK was upgraded successfully but with installer failed.

### Steps to reproduce

having Windows Software Development Kit at version 10.0.22000.832.
run winget upgrade

### Expected behavior

installer exit normally.

### Actual behavior

```
Found Windows Software Development Kit [Microsoft.WindowsSDK] Version 10.0.22621.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package uninstall...
Successfully uninstalled
Starting package install...
Installer failed with exit code: 2008
```

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.1516
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

**Comment by Trenly** [comment]
Seems related to https://github.com/microsoft/winget-cli/issues/1818

**Comment by aetonsi** [comment]
Just happened to me too when going from `10.0.19041.685` to `10.0.22621.2`.
I got the error, then the update disappeared from the `winget upgrade` list, because winget sees version `10.0.22621.2` as currently installed.
The problem is, that's **probably** incorrect. In the `appwiz.cpl` list, the Windows SDK is listed with name `Windows Software Development Kit - Windows 10.0.22621.755` **but** version `10.1.22621.755` (note the minor version change):
![image](https://user-images.githubusercontent.com/18366087/226945288-467b9ec9-1f93-4f18-ab80-3202e0d20efc.png)
But then, if i try to uninstall it, the confirmation popup says:
![image](https://user-images.githubusercontent.com/18366087/226943211-90a27a31-8059-44b1-91eb-317d98957f0d.png)
I thought that maybe the popup is actually asking if i want to uninstall the sdk "_for windows 10.0.22621.755_", this being my current OS version. Problem is, running `cmd /c ver` to see the full OS string, it says `Microsoft Windows [Version 10.0.22621.1413]`.

There's 5 different versions of _things_ involved, `10.0.19041.685`/`10.0.22621.2`/`10.1.22621.755`/`10.0.22621.755`/`10.0.22621.1413`, i'm getting lost..

**Comment by OfekShilon** [comment]
Happens here too:
```
PS C:\Users\ofeks> winget update --all
Name                                                      Id                   Version        Available      Source
-------------------------------------------------------------------------------------------------------------------
WinDbg Preview                                            Microsoft.WinDbg     1.2210.3001.0  1.2303.30001.0 winget
Windows Software Development Kit - Windows 10.0.22000.832 Microsoft.WindowsSDK 10.0.22000.832 10.0.22621.2   winget
2 upgrades available.

(1/2) Found WinDbg [Microsoft.WinDbg] Version 1.2303.30001.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ██████████████████████████████  100%
Successfully installed

(2/2) Found Windows Software Development Kit [Microsoft.WindowsSDK] Version 10.0.22621.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package uninstall...
Successfully uninstalled
Starting package install...
Installer failed with exit code: 2008
```

**Comment by ryfu-msft** [comment]
Similar to #1818 

This is no longer an issue now that different versions of Windows SDK have been separated into their own packages. These package versions should be side-by-side installations rather than a direct upgrade.
