### ISSUE TITLE
Wrong version of VCLib Redist listed

### ISSUE THREAD

**Issue by Greven145** [microsoft/winget-cli#297]
In the manually update section, the following is noted:

> You may need to install the Desktop Bridge VC++ v14 Redistributable Package and the associated Microsoft.VCLibs.140.00.UWPDesktop package. This should only be necessary on older builds of Windows if you get an error about missing framework packages.

After installing the the bridge package on a fresh VM, the appx bundle that is in C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop\14.0\Appx\Retail\x64 is 14,.0.24217. The minimum required version appears to be 14.0.27810.0

**Comment by phil-blain** [comment]
Hi, just want to note this also happened to me today. If I install the VCLibs package dowloaded from [here](https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx), it installs a version that is too old for the latest winget version (https://github.com/microsoft/winget-cli/releases/tag/v1.1.12653, from yesterday). 

If I instead try to install https://github.com/microsoft/winget-cli/releases/tag/v1.0.11692, from June 24, then it works. So maybe the issue is just that the VCLibs packages available at https://docs.microsoft.com/troubleshoot/cpp/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages take a while to be updated to the latest version ?

**Comment by KevinLaMS** [comment]
Thanks. I am following up with Visual Studio.

**Comment by KevinLaMS** [comment]
Greetings.  The VCLibs packages has been updated.  Thanks for reporting.
