### ISSUE TITLE
Implement "winget list --upgradable"

### ISSUE THREAD

**Issue by Hermholtz** [microsoft/winget-cli#3155]
Hello. Bringing to your attention a suggestion that had 67 positive reactions already. Thanks in advance.

```powershell
winget list # lists apps installed by winget
winget list --upgradable # lists only installed apps with available updates
```

_Originally posted by @jantari in https://github.com/microsoft/winget-cli/issues/119#issuecomment-631029541_

**Comment by jantari** [comment]
Thanks for tagging me, I just want to add that that comment of mine is 3 years old and by now we have the PowerShell cmdlets for winget.

Therefore I don't think the legacy DOS command and its syntax matter anymore as it is unusable anyway (due to truncating output etc.)

`winget list --upgradable` is unnecessary because you can just use `Get-WinGetPackage | Where-Object IsUpdateAvailable` instead and get actually usable data from it.

**Comment by Hermholtz** [comment]
On my system there's no "Get-WinGetPackage" nor any other fancy PowerShell stuff.
There _is_ a way to display only upgradable packages by using `winget upgrade` which is totally conterintuitive. Therefore the code is done, please just add this one option `--upgradable` to use it.
