### ISSUE TITLE
Check Wayback Machine instead if the file cannot be found

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/winget-cli#3169]
### Description of the new feature / enhancement

Links sometimes go down for server issues, or other things, and they can be temporarily or permanent. The wayback machine can be more reliable than the actual site, as they are permanent links, as small or insecure sites can get attacked with malware.

### Proposed technical implementation details

If the installer fails to download it will check the Wayback Machine for previous captures of the installer and if none are found the installer fails.

**Comment by Masamune3210** [comment]
Relying on a different service as a fallback without prior permission tends to not win you any favors...

**Comment by Trenly** [comment]
Wayback machine URLs cannot be construed as an official source of the package. Additionally, using wayback for the URLs would place a ton of load on Wayback's servers.

Adding on to that, publishers remove packages for any number of reasons - Security concerns, deprecation, or even just because they want to - and their wishes should be honored. If a user decides to put the installer on wayback or use the installer from wayback, that should be a personal choice. I would venture a guess that this would not be something Microsoft would endorse.

**Comment by denelon** [comment]
The policies for the community repository require packages to come from "official" sources. Several other sources have policies specifically prohibiting their use as a content distribution source and we must honor those policies as well as our own.
