### ISSUE TITLE
[1.5.1881] Missing appDisplayName

### ISSUE THREAD

**Issue by ashemedai** [microsoft/winget-cli#3429]
### Brief description of your issue

Doubleclicking the latest released (1.5.1881) msixbundle shows a dialog window with a missing `ms-resource:appDisplayName` substitution.

### Steps to reproduce

1. Download msixbundle from [1.5.1881](https://github.com/microsoft/winget-cli/releases/tag/v1.5.1881)
2. Doubleclick downloaded file

### Expected behavior

To see the appropriate name instead of a placeholder.

### Actual behavior

The window displays `ms-resource:appDisplayName` instead of the actual application name.

![image](https://github.com/microsoft/winget-cli/assets/610865/a643182e-7b27-4e82-b75a-fc7422f26992)

### Environment

```shell
This is on Windows 10.
```

**Comment by denelon** [comment]
Do you happen to know which version of App Installer you had before the upgrade?

I suspect it's actually a bug in the earlier version of App Installer that has been fixed, but knowing the version number would help to verify.

The App Installer is being used to "install" a newer version of the App Installer, and it's the earlier version displaying that UI.

**Comment by ashemedai** [comment]
> Do you happen to know which version of App Installer you had before the upgrade?

I just went through forced updates at work for this laptop. However, when I submitted this I was on Windows 10 Enterprise 22H2 19045.2006. Can that help you to narrow it down?

**Comment by denelon** [comment]
I wasn't able to get a solid repro, but I installed the oldest release (1.2) and ran the upgrade. It actually failed for a different reason, but I was able to get the update via the Microsoft Store.

I tested the transition from 1.4 to 1.5 and didn't see this behavior.

Without knowing the exact version of App Installer, I doubt I'll be able to reproduce this error. I've talked with the engineering team and was assured this is a bug that was fixed in an earlier version of App Installer.
