### ISSUE TITLE
Winget list sort packages alphabetically

### ISSUE THREAD

**Issue by G0rocks** [microsoft/winget-cli#3542]
### Description of the new feature / enhancement

The problem is that when I'm looking for a package that I think I have installed and I type the winget list command, the results are in a jumbled mess with no apparent order to them.
It would be amazing if the results would be displayed in alphabetical order, that way, reading through the list of packages would be much easier.

I tried seeing if another issue was addressing the same thing but did not find any, please correct me if I'm wrong.

Would be great if somebody could look into this, thank you :)

### Proposed technical implementation details

When the winget list command is entered, winget gathers the list of installed packages, orders it in alphabetical order and then displays the list to the user.

**Comment by jessey-git** [comment]
Yeah, this continues to be one of the most awful user experiences for an otherwise great tool.

There's no way to sort the list by name, or install date, or source, etc. etc.

Best bet is to continue upvoting 1 of the many other issues mentioning the same :(. Here's a few just from a very quick search:

https://github.com/microsoft/winget-cli/issues/1155
https://github.com/microsoft/winget-cli/issues/964
https://github.com/microsoft/winget-cli/issues/3504
https://github.com/microsoft/winget-cli/issues/1769

**Comment by Trenly** [comment]
* Duplicate of #1155 
* Related to #142 
* Related to #1769 
* Related to #1352

**Comment by jcf278** [comment]
Just use like this:

for search apps type
**winget search --name <SOFTWARE_NAME> | sort**

for list installed apps type
**winget list | sort**

**Comment by InfiniteIce2** [comment]
> Just use like this:
> 
> for search apps type **winget search --name <SOFTWARE_NAME> | sort**
> 
> for list installed apps type **winget list | sort**
> 
> the "| sort" will do the alphabetically sort

thanks, | sort worked perfectly.  Weird how  I can't find it in any -help outputs from winget list etc..

winget list | sort this does indeed sort alphabetically, although i feel like that should be the default, thanks!

**Comment by SharakPL** [comment]
@jcf278 thanks, `sort` helps a lot, but it looks like it uses different encoding so the results get messed up:

**`winget list` (I'm guessing UTF-8)**
`Zdjęcia Microsoft                       MSIX\Microsoft.Windows.Photos_2025.1112… 2025.11120.5001…`

**`winget list | sort` (definitely not UTF-8)**
`Zdj─Öcia Microsoft                       MSIX\Microsoft.Windows.Photos_2025.1112ÔÇŽ 2025.11120.5001ÔÇŽ`

Does anyone know how to have a properly encoded list as a result of `| sort`?

Edit: found a simple fix, just add this to the powershell profile:
```
$OutputEncoding = [System.Console]::InputEncoding = [System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8
```
___

@InfiniteIce2 you can't find it because `sort` is not a part of winget-cli. It's an alias of `Sort-Object` utility of Powershell.

`help sort` or go to https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/sort-object?view=powershell-7.5
