### ISSUE TITLE
Scope needed on portable Packages

### ISSUE THREAD

**Issue by Speed7811** [microsoft/winget-cli#3748]
### Brief description of your issue

I want that my portable app should be installed on scope machine. I can do this by "winget install myapp --scope machine". But If I add this to my manifest file i got the warning "Manifest Warning: Scope is not supported for InstallerType portable."

When I use "ElevationRequirement: elevationRequired" instead the option seems to be ignored.

### Steps to reproduce

1. Add "Scope: machine" to the installer manifest file
2. winget validate --manifest "PATH_TO_MY_MANIFEST_DIR"

### Expected behavior

The option Scope will be used because the user can use is directly when he enters: "winget install myapp --scope machine"

### Actual behavior

- Manifest Warning: Scope is not supported for InstallerType portable.
- Option is ignored

### Environment

```shell
Windows-Paket-Manager v1.6.2771
```

**Comment by mdanish-kh** [comment]
> Manifest Warning: Scope is not supported for InstallerType portable.

This is because WinGet already supports installing portables in both `user` and `machine` scope. It is not needed to specify it in the manifest.

You can use the command `winget install <portable_app> --scope <scope>` to install the portable app in the desired scope

**Comment by Speed7811** [comment]
Yes I know about the option. But I don't want that the user should do the decision. My software package (=> the developer) should do the decision how the software should be installed successfully.

**Comment by denelon** [comment]
This is the first time I've seen a portable package needing to be installed in a specific scope. I think supporting the elevation requirement might be the better way to go rather than splitting into scopes.

**Comment by mdanish-kh** [comment]
@Speed7811 Regarding the portable app, are you referring to `Speed-Soft.Pingt` mentioned in https://github.com/microsoft/winget-cli/issues/3749? 

> This is the first time I've seen a portable package needing to be installed in a specific scope.

I can't seem to reproduce the same issue as the author. For me, the portable app installs just fine in both scopes.



https://github.com/microsoft/winget-cli/assets/88161975/87a9488c-a508-4fc3-8a44-cb8944f4ffac


Note: I don't have to open a new instance of Terminal since newer versions of Terminal support refresh of PATH variable in a new tab

**Comment by Trenly** [comment]
>  But I don't want that the user should do the decision. My software package (=> the developer) should do the decision how the software should be installed correctly.

The whole point of a portable application is that it shouldn't need specific privileges to install. If a user were to download the application and put it into their documents folder and add that to their path environment variable, they could do that. If a user were to download it and put it in "Program Files" and add it to the machine scoped Path environment variable, they could also do that. 

If you want your application to install a specific way, then you should build an installer for it using inno, or nullsoft, or wix, installshield, install4j, or any of the myriad of tools available that are specifically designed for publishers to control how their application gets installed.

I strongly believe that requiring a specific scope or elevation for portable installs should not be supported, as it is fundamentally an anti-pattern and goes against the core tenets of the purpose for having a portable application instead of an installer.

**Comment by Trenly** [comment]
> This is the first time I've seen a portable package needing to be installed in a specific scope. I think supporting the elevation requirement might be the better way to go rather than splitting into scopes.

@denelon - I don't think this is actually the case. Per my reply above, by the very definition of a portable application there can be no requirement to install in a specific scope. Could there be an edge case where the application requires administrator privileges to run properly? That I could maybe understand. But for the actual install itself, I find it almost impossible to believe there would be any form of scope requirement

**Comment by Speed7811** [comment]
@mdanish-kh - Yes I'm referring to Speed-Soft.Pingt mentioned in #3749. If I do it like in your video I get the same results. Please open a new "cmd" (unelevated) after installing it and enter "pingt". It will not work.

@Trenly - If this is really an anti pattern why is this option supported on the command line? If this is really an anti pattern the option "--scope" should be not supported if the installer type is "portable". 

The app itself doesn't need the scope. I only need the scope because otherwise the user cannot execute the app in an unelevated window. If I install the app with the scope option it works in an elevated and unelevated window. Please see #3749 - I think if this issue is solved I don't have any problems. At the moment I must gave the users the information to install it with this command "winget install -e pingt --scope machine" - otherwise the app cannot be executed in an unelevated window.

Addionally I cannot find any hint in the documentation that the scope option is not supported on the portable installer type. If I check the manifest here https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.5.0/installer.md I cannot find any information about this - or are there any other docs I didn't find?

**Comment by Trenly** [comment]
> If this is really an anti pattern why is this option supported on the command line?

Because it determines which Path environment variable gets written and the file location. Its basically the user saying whether they want to put it in a location only accessible by them or a location accessible by anyone.

Apologies for not being clear - What I meant by "it" being an Anti-Pattern is not that it can be installed in either scope, the Anti-Patrern would be *only* allowing it in machine scope.

**Comment by Speed7811** [comment]
For me this issue is clear now and I will close it. I think if the bug in #3749 is solved I don't have any troubles.
