### ISSUE TITLE
unpriviledged mode

### ISSUE THREAD

**Issue by hex-m** [microsoft/winget-cli#3810]
### Description of the new feature / enhancement

We (the IT department) want to give our users easy access to common applications and utilities without giving them admin permissions on their workplace-computers. For this use case we would need a mode in which winget only shows packages that can be installed an updated without elevation.

### Proposed technical implementation details

Ideally we would set a system-wide configuration to disable all winget-features that need elevated permissions.

UPDATE:

After reading #388 I assume for this to work consistently, it is necessary to exclude anything that is not an MSI(X) package.

**Comment by hex-m** [comment]
Not sure what valid means in this case. The [submission documentation](https://learn.microsoft.com/en-us/windows/package-manager/package/repository#submission-expectations) says:

> All manifest entries are accurate and not misleading.

So what you say is that even when restricting the InstallerType, there is no way to automatically check if the manifest is lying?

**Comment by denelon** [comment]
The installer type is validated.

The part that is unknown (because it is not a requirement in the schema) is whether the scope or elevation requirements are completely accurate.

From an automated validation perspective, we test that the properties in the manifest are correct, but we don't try to validate the cases not declared in the manifest.

For example, a manifest could include scope "user", but may exclude scope for "machine". We wouldn't try to validate that a machine wide installation succeeds in that case because it's support or lack thereof is not explicit.

If a manifest has an elevation requirement, we do not validate that the other elevation requirements would not succeed.

I can point to "Spotify" as an example. It will not run elevated, and the manifest declares this. If this were to change in the future and the manifest was not updated, we wouldn't know to automatically check to see if it could succeed elevated during validation.

**Comment by hex-m** [comment]
So this issue depends on [mandatory scope definition](https://github.com/microsoft/winget-cli/issues/2097) in the manifest and something analogous for elevation requirements.

I found that similar topics were discussed in https://github.com/microsoft/winget-cli/issues/1898, #3240, #2097 and #847. So I close this issue as it doesn't bring new ideas or requirements to the table.

Thank you for the explanations.
