### ISSUE TITLE
winget doesn't understand some of the commands

### ISSUE THREAD

**Issue by sayedarifuddin** [microsoft/winget-cli#423]
### Powershell
![image](https://user-images.githubusercontent.com/47639147/84597779-002dac80-ae88-11ea-8efa-3ada49d13fbf.png)
### Command Prompt
![image](https://user-images.githubusercontent.com/47639147/84597836-5d296280-ae88-11ea-9e4d-bf585f7186ae.png)
### winget version (Microsoft.DesktopAppInstaller v1.0.41331.0)
![image](https://user-images.githubusercontent.com/47639147/84597907-d3c66000-ae88-11ea-9055-ccb550a80250.png)

**Comment by megamorf** [comment]
Hey @sayedarifuddin, thanks for taking the time to report this. It's a known user experience issue so please use the --exact (-e) switch to make winget treat the search string as literal instead of attempting a substring match.

Since there are already open issues for this problem yours can be considered a duplicate, so please close it and subscribe to the following issues instead:

#282
#292
#301

**Comment by LoZeno** [comment]
Hello, Even using the `--exact` switch it seems to confuse winget:
![image](https://user-images.githubusercontent.com/3267561/84632707-35b5b280-aee7-11ea-8ac8-31b0a3f71a68.png)
![image](https://user-images.githubusercontent.com/3267561/84632739-41a17480-aee7-11ea-8cef-dab63de3fa2a.png)
![image](https://user-images.githubusercontent.com/3267561/84632759-49611900-aee7-11ea-9abe-31b7a65ccd05.png)

**Comment by megamorf** [comment]
@LoZeno The command is case sensitive. You're searching for `Powershell` but should be searching for `PowerShell` instead.
