### ISSUE TITLE
winget install PowerShell : Multiple apps found matching input criteria. Please refine the input.

### ISSUE THREAD

**Issue by MostHated** [microsoft/winget-cli#430]
# Brief description of your issue
Upon trying to figure out the best way to update PowerShell, I figured I would give winget a try, but when I input ```winget install powershell``` "gives Multiple apps found matching input criteria. Please refine the input."
The ID of the package is Microsoft.PowerShell, so I tried ```winget install Microsoft.Powershell``` same error.  

![](https://i.imgur.com/cx6JwDa.png)

# Steps to reproduce

See above. 
# Expected behavior

Downloads the listed PowerShell version. 
# Actual behavior

Tells me to refine input, even if I input the actual full ID.

# Environment

```none
Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.
Windows: Windows.Desktop v10.0.19041.264
Package: Microsoft.DesktopAppInstaller v1.0.41331.0  


```

# Personal Recommendation 

It would be great if, when your available options are narrowed down, to have the ability to select the one you want to install if it is not going to accept what you have typed similar to the mechanic seen below when using tab to select a folder.

![](https://i.imgur.com/qYYMwg6.gif)

**Comment by megamorf** [comment]
Hey @MostHated, thanks for taking the time to report this. It's a known user experience issue so please use the `--exact` (`-e`) switch to make winget treat the search string as literal instead of attempting a substring match. Please note that the term is case-sensitive. 

Since there are already open issues for this problem yours can be considered a duplicate, so please close it and subscribe to the following issues instead:

* #282
* #292
* #301
