### ISSUE TITLE
Update PowerShell SDK Version

### ISSUE THREAD

**Issue by skanda890** [microsoft/winget-cli#4369]

**Comment by yao-msft** [comment]
This issue was originally created to track the security vulnerabilities listed [here](https://github.com/skanda890/winget-cli/pull/3) The fixes are already made with https://github.com/microsoft/winget-cli/pull/4083 and https://github.com/microsoft/winget-cli/pull/3495 and https://github.com/microsoft/winget-cli/pull/3355

So closing this issue.
