### ISSUE TITLE
App Installer failed to install package dependencies. Ask the developer for  package. 

### ISSUE THREAD

**Issue by echobravo2** [microsoft/winget-cli#437]
# Brief description of your issue

Tried to install the winget package from a release and got an error:
"App Installer failed to install package dependencies. Ask the developer for package. "

I think the package trying to access the "store" which is blocked in the company's own machine.

# Steps to reproduce
1.downloaded the package from
https://github.com/microsoft/winget-cli/releases/download/v0.1.4331-preview/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
2. entered cmd on the downloaded path and execute

# Expected behavior
installing the package from 0 to 100%

installed to 7%, then stopped with the error message.

**Comment by echobravo2** [comment]
I just want to point out that the Microsoft store has been blocked wide by our company IT policy, and there is no way around it.  
The request is to enable the installation of the winget-cli without any dependency to store.

**Comment by CBielstein** [comment]
@echobravo2 I hit this issue running a manual installation due to my company's IT policy blocking the Microsoft Store as well. I'm on Windows 1909 and installing the [VC++ v14 Desktop Framework Package](https://docs.microsoft.com/en-us/troubleshoot/cpp/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages) appears to have resolved the issue. This was noted in the readme for "older versions of Windows 10," which I'm now guessing includes 1909.

Maybe the same trick would help you?

**Comment by denelon** [comment]
@echobravo2  did the note from https://github.com/microsoft/winget-cli#manually-update work for you?

**Comment by echobravo2** [comment]
@denelon it works, thanks

**Comment by Allixandree** [comment]
it gave me the same error. why tho it was fine until today

**Comment by denelon** [comment]
@allixandtree you may need to force an install from the "msstore" to get dependencies. Once it's "working" then you should be able to install any of the previews if you're not an "insider" or you can stay on the "stable" release. You may also be able to "Repair" via Windows Apps & Features if you're on Windows 11.
