### ISSUE TITLE
403 Forbidden on Kate package

### ISSUE THREAD

**Issue by gaetgu** [microsoft/winget-cli#441]
While installing the Kate package, a fatal `Forbidden (403)` is thrown.

To reproduce this, I ran `winget install Kate` twice, after restarting my computer and trying on a different computer.

I expected this to install *Kate*, like it has when I have installed other apps with `winget`.
Instead, it gave this output:

![output, with 403](https://i.ibb.co/j4Y9Msc/image.png])

```bash
Found Kate [KDE.Kate]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/909/artifact/kate-20.04.1-909-windows-msvc2019_64-cl-sideload.appx
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190193 : Forbidden (403).
```

This seems to be an issue on their part, probably removing public access to the file, but `winget` should also be updated to account for this.

# Environment

```none
[winget --info]

Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.329
Package: Microsoft.DesktopAppInstaller v1.0.41331.0
```

**Comment by megamorf** [comment]
@gaetgu So you expect the winget cli error message to be more detailed in case the installer cannot be retrieved, like:

**HTTP 403 / HTTP 404 / HTTP 410**
The package $PackageName appears to not available anymore. Please open an issue on https://github.com/microsoft/winget-pkgs/issues with $PackageName, $PackageVersion, $PackageURL.

**HTTP 502 / HTTP 503 / HTTP 504**
The package $PackageName cannot be downloaded because the vendor's servers are currently unavailable. Please try again later.

**Comment by gaetgu** [comment]
> @gaetgu So you expect the winget cli error message to be more detailed in case the installer cannot be retrieved, like:
> 
> **HTTP 403 / HTTP 404 / HTTP 410**
> The package $PackageName appears to be not available anymore. Please open an issue on https://github.com/microsoft/winget-pkgs/issues with $PackageName, $PackageVersion, $PackageURL.
> 
> **HTTP 502 / HTTP 503 / HTTP 504**
> The package $PackageName cannot be downloaded because the vendor's servers are currently unavailable. Please try again later.

Yes, that would be great. It would be great if they could get a new working link, but if they can't/won't, then yes, a more detailed output would be great.

**Comment by megamorf** [comment]
@gaetgu Ah, sorry your issue is not a general request for improved error messages, instead you specifially meant to report that the `Kate` package installation is broken? If the latter is the case then you should open a bug report on https://github.com/microsoft/winget-pkgs/issues because the winget-cli repository deals with the winget program itself rather than its packages,

**Comment by gaetgu** [comment]
Alright, will do.

**Comment by megamorf** [comment]
@gaetgu I believe it makes sense to re-open this issue since improving the user experience by providing clear and actionable messages in case of errors like these should be in the backlog :-)

**Comment by diasdmhub** [comment]
I guess the error messages and improved user experience have not been updated yet.
I'm using Winget v1.6.3133 and it still shows a generic error.
```psw
PS > winget install kde.okular
(...)
Download request status is not success.
0x80190193 : Forbidden (403).
```
@gaetgu's suggestion seems good enough for me.

**Comment by cjwijtmans** [comment]
now it shows 

> An unexpected error occurred while executing the command:
> Download request status is not success.
> 0x80190193 : unknown error

even worse.

**Comment by BOY0038v2** [comment]
same problem 3 years later yikes...
