### ISSUE TITLE
Winget.it is down, or how to winget should validate repositories

### ISSUE THREAD

**Issue by carloshm** [microsoft/winget-cli#442]
# Brief description of your issue

trying to install Heidi failed: winget install AnsgarBecker.HeidiSQL --exact

Found HeidiSQL [AnsgarBecker.HeidiSQL]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.winget.it/dl/99bd666018b03817bbb114b4e65beb76a53d9a1bbf693a568944009f36039ed5/https://www.heidisql.com/installers/HeidiSQL_11.0.0.5919_Setup.exe
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072ee7 : unknown error

# Steps to reproduce
winget install AnsgarBecker.HeidiSQL --exact

# Expected behavior

download and install the tool
Potential CDN to stay current with available published tools woule be an option

# Actual behavior
It seems winget.it is down (Europe)

# Environment
Windows 10 2040, insider, latest winget, launching directly url does not resolve server
```none
[winget --info]
Windows Package Manager version
Windows: Windows.Desktop version
Package: Microsoft.DesktopAppInstaller version

Windows Package Manager v0.1.41331 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.329
Package: Microsoft.DesktopAppInstaller v1.0.41331.0

Links:
  Privacy Statement: https://aka.ms/winget-privacy
  License agreement: https://aka.ms/winget-license
  3rd Party Notices: https://aka.ms/winget-3rdPartyNotice
  Homepage:          https://aka.ms/winget

Any other software?
```

**Comment by megamorf** [comment]
Hey @carloshm, thanks for reporting this. However, the issue you're facing is a problem with the url in the HeidiSQL package metadata. The winget-cli repository is about the winget program itself whereas you're reporting a problem with a winget package which is tracked in winget-pkgs.

Please open an issue [here](https://github.com/microsoft/winget-pkgs/issues) referencing an issue with the URL:
https://github.com/microsoft/winget-pkgs/blob/master/manifests/AnsgarBecker/HeidiSQL/11.0.0.5919.yaml#L19

**Comment by SoftCreatR** [comment]
Short answer: https://github.com/microsoft/winget-pkgs/pull/1668#issuecomment-643803796 

I took it down, because @KevinLaMS started declining all packages using the Winget.it proxy service that has been set-up as a temporary solution for some connection bugs (e.g. https://github.com/microsoft/winget-pkgs/issues/91).

**Comment by carloshm** [comment]
Thanks @megamorf I enter here (and submitted a pull rq for packages), so I expected any winget available tool should be...available. The tool is not related to winget, but as long as it is "managed" and "published" I would say that users expect to not being advertised. So, should winget implement:?
- validation tool is ready for download, or at least periodically checked
- available through CDN from Azure or thrid party that validates the checksum

**Comment by carloshm** [comment]
> Short answer: [microsoft/winget-pkgs#1668 (comment)](https://github.com/microsoft/winget-pkgs/pull/1668#issuecomment-643803796)
> 
> I took it down, because @KevinLaMS started declining all packages using the Winget.it proxy service that has been set-up as a temporary solution for some connection bugs (e.g. [microsoft/winget-pkgs#91](https://github.com/microsoft/winget-pkgs/issues/91)).

Thanks. I think winget should manage the experience in some way. On the other hand, we could have a mess experience with a lot of apps not running effectively.
Thinking in how Stores works. They are thrid party, so I expect to be able to install them, and not blame the developer.
Some previous ideas to vote, and add as bug&feature

**Comment by SoftCreatR** [comment]
I could easily bring it back online and continue serving the assets until they fixed the validation issues (and even continue automatic publishing of updates), but that wouldn't change anything, because at least @KevinLaMS would continue declining them. All the effort I put into this would be just a waste of time. 

As you may have noticed, your PR failed due to the validation issues mentioned before. And since there's no other, official mirror, you'll have to wait until the validation issues have been fixed in order to obtain HeidiSQL and some other applications using winget. Or @KevinLaMS get's in touch with me (@denelon has my personal email address, just in case) so we can figure out a solution that works for all of us.

Taking down Winget.it was more a knee-jerk reaction than a planned one.

**Comment by denelon** [comment]
@SoftCreatR, @KevinLaMS and I are looking at a few options.

**Comment by denelon** [comment]
We've made quite a few changes over the last year with validation, and automation. We still regularly encounter problems with hosts that either block Azure IP address ranges or look for specific user agent strings. There are no plans to cache programs coming from third party CDNs. Many ISVs and publishers prohibit this behavior. We now also run daily scans on installers we're unable to install or have changes that invalidate the hash in manifests. We've attempted to automatically fix as many of these as the system can. In the event the system can't we create "Help-Wanted" Issues in the winget-pkgs repository.  I'm going to go ahead and close this Issue.
