### ISSUE TITLE
I steel can't to download discordptb

### ISSUE THREAD

**Issue by Kadisa13** [microsoft/winget-cli#4474]
I steel can't to download discordptb

**Comment by stephengillie** [comment]
Hi @Kadisa13,

Why can't you download `Discord.Discord.PTB`? What error do you get? Could you share the logs when you try? 

A package problem is more likely than a CLI problem here, since issues with other packages weren't reported, so might need to be moved to the [winget-pkgs](https://github.com/microsoft/winget-pkgs/) repo, but I can't be sure without more data.

**Comment by denelon** [comment]
@Kadisa13 I'm not able to reproduce the failure. Can you share logs for when this is happening? You can append "--verbose-logs --logs" to the end of the command to enable verbose logs and open the folder containing the log.
