### ISSUE TITLE
Make Microsoft.WinGet.Client PowerShell cmdlets "singular" in name

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#4680]
### Description of the new feature / enhancement

The following cmdlets are plural in name and should be singular:
* Get-WinGetSettings
* Get-WinGetUserSettings
* Set-WinGetUserSettings
* Test-WinGetUserSettings

**Comment by denelon** [comment]
These should be made into "singular" names, and the "plural" name should become an alias so users who have scripted against this aren't broken.

**Comment by jantari** [comment]
> [...] the "plural" name should become an alias so users who have scripted against this aren't broken.

F*** 'em. Break it now while it's still fresh, you don't wanna become the [ShellFolders](https://devblogs.microsoft.com/oldnewthing/20031103-00/?p=41973) of the 21st century. No alias!

**Comment by kilasuit** [comment]
@denelon I'll add this into the following PR #4716

**Comment by ThomasNieto** [comment]
There is an anti-pattern when putting all "settings" into a single cmdlet. Ideally there would be a cmdlet(s) to set the individual setting.

Here are some examples that aren't real WinGet values.

```powershell
Disable-WinGetHashValidation
Enable-WinGetHashValidation

Set-WinGetTimeout
Get-WinGetTimeout
```

Lets take `Get-WinGetSettings` cmdlet. The output is not user friendly at all. First it returns a case sensitive hashtable. The is not a good way to parse the settings at a glance. There is not an easy way for me to determine which settings I can set with `Set-WinGetSettings` since it takes a hashtable which could be anything.
