### ISSUE TITLE
Support edge chromium addons

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-cli#618]
# Description of the new feature/enhancement
Installing edge chromium addons using winget. For example, "winget install tampermonkey" adds tampermonkey to edge chromium.
This feature is useful if your native app depends on a browser addon to provide features such as web clipping. Winget users won't need to manually install this addon from [edge web store](https://microsoftedge.microsoft.com/addons/) or [chrome web store](https://chrome.google.com/webstore/category/extensions) after installing your native app from winget, which can improve user experience.

# Proposed technical implementation details (optional)

There are 2 methods.
1. Using a manifest to provide download link of crx (like exe/msi packages already in the winget-cli repo). Take pakku as an example.
```
Id: xmcp.pakku
Version: 10.0.4
Name: pakku
Publisher: xmcp
License: GPL
LicenseUrl: https://github.com/xmcp/pakku.js/blob/master/LICENSE.txt
Tags: edge addon,bilibili,danmu,video
Description: Automatically removes duplicate danmu while watching videos on bilibili.com.
Homepage: http://s.xmcp.ml/pakkujs/
Installers:
  - Arch: x64
    Url: http://s.xmcp.ml/pakkujs/latest.crx
    Sha256: f5193c2f3528e2cf28148276fe5cd0e7dbd07c4f75cf072bab87cb50b150f64e
    InstallerType: crx
```
2.download and install addons from [edge web store](https://microsoftedge.microsoft.com/addons/) and [chrome web store](https://chrome.google.com/webstore/category/extensions)

**Comment by jedieaston** [comment]
The only problem with this is that Chromium (and therefore Edge) don't support installing extensions outside of either the user consenting inside the Web Store or Group Policy/MDM (Edge's docs are [here](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#extensions-policies) for the policy options). 

You could install these via adding the extension ID to the registry and telling the user to restart their browser, but then it begs the question of why not just have the administrator use the Group Policy template (since it's easier to track that). Also, the Chrome Web Store (I don't know about Edge's) doesn't make previous versions of extensions available and automatically updates extensions when the browser starts, so that'd have to be dealt with (version: latest would become a way of life for these, which is fine, just something to note). 

This decision was made by the Chrome developers to prevent a whole host of malware that would install extensions without consent, which is made harder if you have to do it through GPO/MDM (and the extension has to be on the presumably secure Chrome Web Store).

**Comment by upintheairsheep** [comment]
> The only problem with this is that Chromium (and therefore Edge) don't support installing extensions outside of either the user consenting inside the Web Store or Group Policy/MDM (Edge's docs are [here](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#extensions-policies) for the policy options).
> 
> You could install these via adding the extension ID to the registry and telling the user to restart their browser, but then it begs the question of why not just have the administrator use the Group Policy template (since it's easier to track that). Also, the Chrome Web Store (I don't know about Edge's) doesn't make previous versions of extensions available and automatically updates extensions when the browser starts, so that'd have to be dealt with (version: latest would become a way of life for these, which is fine, just something to note).
> 
> This decision was made by the Chrome developers to prevent a whole host of malware that would install extensions without consent, which is made harder if you have to do it through GPO/MDM (and the extension has to be on the presumably secure Chrome Web Store).

https://superuser.com/questions/1650457/installing-chrome-extension-via-cli
