### ISSUE TITLE
`winget download`

### ISSUE THREAD

**Issue by Rakib** [microsoft/winget-cli#658]
# Description of the new feature/enhancement

I want to install notepad++ but maybe not trough winget but just want to download the package, and also choose the package format, msi or msix.

This to have one place to download my apps. 

# Proposed technical implementation details (optional)

**Comment by denelon** [comment]
Are you asking for some kind of "download only" function?

The manifests are essentially pointing to the source for the installers. We wouldn't have the ability to provide installer types that aren't available.

**Comment by Rakib** [comment]
Both basically, since MS is pushing MSIX in the enterprise. It would be nice to be able to download .msix files from winget since most apps are not available in that format from their respective homepage.

**Comment by thbch** [comment]
An enhancement of having a "download" only functionality would make sense for us as well. This would allow for a separation of downloading and installation.

**Comment by JoergWu** [comment]
Would it not even be better simply to integrate the download / caching in "Delivery Optimization" and/or "BranchCache"?

**Comment by denelon** [comment]
command:
`winget download <package>`

The typical options should be included here relative to search and install when specifying the package.

options:
`--path <path>`
`--installer-architecture <architecture>`
`--installer-locale <locale>`
`--installer-platform <platform>`
`--installer-scope <scope>`
`--installer-type <type>`

If these options are not specified, the installer that would have been selected by the default Windows Package Manager settings for `winget install <package>` would apply.

Typical output:

`Downloading <package name> version <version> from <source> source via <installer URL>.`

It's possible the user settings (requirements) or specified options cannot be met when attempting to locate an installer.
`ERROR: Unable to locate <package> installer with specified options or required settings.`

Some of the packages (non-Win32) from the Microsoft Store are prohibited from direct download due to licensing or agreements.
`ERROR: Unable to download Microsoft Store package.`

**Comment by MarcoPeraza** [comment]
Great idea. Would it be possible to then point winget at the downloaded files when you do want to install? I guess that would be similar to a cache feature.

**Comment by denelon** [comment]
[Discussion](https://github.com/microsoft/winget-cli/discussions/2911#discussioncomment-4857962) on cache management and reference to how this may be incorporated with a "winget download" capability.

**Comment by JoergWu** [comment]
Actually especially the download capabilities for store apps is very important. Due to the fact that MS Store for Business connection went away soon there is only the capability to use Intune to get the apps installed then. I have customers with large install base still using SCCM. They have infra not connected to the internet. Other infras are only reachable by expensive satellite connections so we can not point every client to Intune. We need more control on how and when apps are installed and transferred to remote sites.

Regarding licensing admins can accept EULAs for end users since decades for MS stuff. We have even the same feature within winget-cli for the store stuff where you have to accept MS EULA as well. So this should not be a road blocker.

**Comment by denelon** [comment]
Related to:
* #578

**Comment by jonnygoogle25** [comment]
+1 for this feature.  Microsoft does not make it easy to obtain appx package files and we need a way to deploy these internally as well

**Comment by denelon** [comment]
We're currently working on this feature.

**Comment by rokejulianlockhart** [comment]
@denelon, since this now exists, perhaps we could let not-currently-installable formats like `.zip` into the repo, so that they can be downloaded from a trusted source?

**Comment by jonnygoogle25** [comment]
@denelon - I'm testing out teh RC build of 1.6 and it seems like whenever I try to download AppX source files I get a "0x80070032: the Request is not supported"

Is this expected?  MSI seems to work fine

**Comment by RDMacLachlan** [comment]
> @denelon - I'm testing out the RC build of 1.6 and it seems like whenever I try to download AppX source files I get a "0x80070032: the Request is not supported"
> 
> Is this expected? MSI seems to work fine

This is expected when attempting to download appx or msix apps from the Microsoft Store source. There is still some pending work to enable downloading those specific apps.

Note! This will only be supported for Micosoft Store UWP apps which have been opt-ed in for offline distribution when published to the Microsoft Store. This will be the same list of apps that are available when using the Microsoft Store for Business to download.

**Comment by nathan-omeara** [comment]
> > @denelon - I'm testing out the RC build of 1.6 and it seems like whenever I try to download AppX source files I get a "0x80070032: the Request is not supported"
> > Is this expected? MSI seems to work fine
> 
> This is expected when attempting to download appx or msix apps from the Microsoft Store source. There is still some pending work to enable downloading those specific apps.
> 
> Note! This will only be supported for Micosoft Store UWP apps which have been opt-ed in for offline distribution when published to the Microsoft Store. This will be the same list of apps that are available when using the Microsoft Store for Business to download.

Is there an expected timeline when this pending work will be done?  I noticed that a fully updated GA Win11 now includes winget 1.6.2771, which includes this download command, but I still see the same `0x80070032: the Request is not supported` error.

**Comment by Rakib-Ul-Haque** [comment]
hellwo
