### ISSUE TITLE
Can't run winget from WSL

### ISSUE THREAD

**Issue by mignz** [microsoft/winget-cli#688]
I have installed Debian and can't run `winget.exe` using bash:

![Screenshot](https://user-images.githubusercontent.com/358114/82838500-5da38e80-9ec4-11ea-8a5d-17f893344ac2.png)

The `winget install ...` command also doesn't install the App in Windows.

**Comment by bitcrazed** [comment]
That's a rather old version of Winget - could you please update to a recent build https://github.com/microsoft/winget-cli/releases

**Comment by mignz** [comment]
Just tried v0.2.10191 and for me it's still not working. If it helps to reproduce, I'm using Debian from the MS store.

**Comment by craigloewen-msft** [comment]
This is an error related to the Windows Subsystem for Linux! We added support to use app execution aliases in Windows 10 build 20190 and higher. As of writing this comment the fix is only available on Windows Insider builds, meaning you'll need to upgrade your build to get this working.

As a workaround in the meantime, @mignz if you run `powershell.exe /c winget.exe --info` do you get a good output?
