### ISSUE TITLE
Trouble displaying special characters. Unicode/utf8 problem. In some circumstances..

### ISSUE THREAD

**Issue by ntaken** [microsoft/winget-cli#705]
# Brief description of your issue

Windows Powershell have trouble displaying special characters. Unicode/utf8 problem. 

Similar problem with App Installs Alias for python/python3 error. 

winget display correctly for cmd and Powershell 7(windows terminal) but both fail to display the error message for Alias correctly.

# Steps to reproduce

![unicodeprob](https://user-images.githubusercontent.com/71373110/105062421-e20dd780-5a7a-11eb-94d0-d5e8aaea513c.jpg)

# Expected behavior

Being able to display åäö.

# Actual behavior

See the screenshot.

# Environment

Microsoft Windows [Version 10.0.19042.746]

[winget --info]
Windows Package Manager version v0.2.3162
Windows: Windows.Desktop version v10.0.19042.746
Package: Microsoft.DesktopAppInstaller version  v1.11.3162.0

**Comment by ntaken** [comment]
Fixed the Windows PowerShell console by changing the font from bitmap to a True Type font like Consolas or Cascadia.

The problem with Alias remain. I understand that this may not be the right place for reporting that but I have no clue where to actually report it.

**Comment by JohnMcPMS** [comment]
No matter what, if connhost.exe is your console renderer, you need to select a font that contains all of the characters that will be output.  It doesn't have any fallback capability, and I have it on good authority from that team that it likely never will.  Terminal does have fallback, so you have a lot more flexibility on font choice.

I think Feedback Hub is probably the right place to submit the alias problem.  But on accident you found the right person, because that is totally my fault.  I was adding it quickly per a request and didn't do the due diligence to set the the CP.

**Comment by ntaken** [comment]
Thanks, I appreciate the response. Now it all make sense. Will be using Windows terminal going further anyway.
